function R = st_configure_signal_editors()
%ST_CONFIGURE_SIGNAL_EDITORS Configure existing harness Signal Editor blocks.
% - Direct CUT Inport exists: SampleTime=0.01 and first scenario rename.
% - Input values/waveforms are not changed.
%
% Detailed checkpoints are controlled by cfg.VerboseLogging.

cfg = st_require_runtime_target();
T = st_load_targets(cfg.OnlyEnabled);
st_force_model_stopped(cfg.TopModel);

n = height(T);
SignalEditorBlock = strings(n,1);
DataFile = strings(n,1);
OldScenario = strings(n,1);
NewScenario = strings(n,1);
Status = strings(n,1);
Message = strings(n,1);
ElapsedSec = zeros(n,1);
Timestamp = strings(n,1);

totalTimer = tic;

st_log(cfg, 'INFO', ...
    'Configure Signal Editor start | count=%d', ...
    n);

for i = 1:n

    ownerPath = ...
        st_normalize_cut_path( ...
            T.CUTPath(i), ...
            cfg.TopModel);

    harnessName = ...
        char(T.HarnessName(i));

    scenarioName = ...
        st_scenario_name( ...
            T.CUTName(i));

    NewScenario(i) = ...
        string(scenarioName);

    timerValue = tic;

    st_log(cfg, 'DEBUG', ...
        '[SignalEditor %d/%d] start | CUT=%s | Harness=%s | Scenario=%s', ...
        i, n, ownerPath, harnessName, scenarioName);

    try

        st_log(cfg, 'TRACE', ...
            '[SignalEditor %d/%d] searching direct CUT Inports', ...
            i, n);

        inports = ...
            find_system( ...
                ownerPath, ...
                'SearchDepth', 1, ...
                'Type', 'Block', ...
                'BlockType', 'Inport');

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] direct Inport count=%d', ...
            i, n, numel(inports));

        if isempty(inports)

            Status(i) = 'SKIP_NO_INPORT';
            Message(i) = 'CUT has no direct Inport';

            ElapsedSec(i) = toc(timerValue);

            Timestamp(i) = ...
                string(datetime( ...
                    'now', ...
                    'Format', ...
                    'yyyy-MM-dd HH:mm:ss'));

            fprintf( ...
                '[%d/%d] SKIP %s: no direct Inport\n', ...
                i, n, char(T.CUTName(i)));

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] skipped | elapsed=%.3f sec', ...
                i, n, ElapsedSec(i));

            continue;
        end

        st_log(cfg, 'TRACE', ...
            '[SignalEditor %d/%d] force model stopped', ...
            i, n);

        st_force_model_stopped(cfg.TopModel);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] harness.load start', ...
            i, n);

        sltest.harness.load(ownerPath, harnessName);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] harness.load done', ...
            i, n);

        st_log(cfg, 'TRACE', ...
            '[SignalEditor %d/%d] locating Signal Editor block', ...
            i, n);

        sigBlock = ...
            st_find_signal_editor_block(harnessName);

        SignalEditorBlock(i) = ...
            string(sigBlock);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] block=%s', ...
            i, n, sigBlock);

        set_param( ...
            sigBlock, ...
            'SampleTime', ...
            cfg.SignalEditorSampleTime);

        st_log(cfg, 'TRACE', ...
            '[SignalEditor %d/%d] SampleTime applied=%s', ...
            i, n, cfg.SignalEditorSampleTime);

        options = ...
            st_normalize_options( ...
                get_param( ...
                    sigBlock, ...
                    'options@ActiveScenario'));

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] scenario option count=%d', ...
            i, n, numel(options));

        if isempty(options)

            error( ...
                'Signal Editor has no scenario: %s', ...
                sigBlock);
        end

        oldName = ...
            options{1};

        OldScenario(i) = ...
            string(oldName);

        fileName = ...
            get_param( ...
                sigBlock, ...
                'Filename');

        matPath = ...
            st_resolve_data_file( ...
                fileName, ...
                cfg.TopModel);

        DataFile(i) = ...
            string(matPath);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] data file=%s | oldScenario=%s | newScenario=%s', ...
            i, n, matPath, oldName, scenarioName);

        if ~strcmp(oldName, scenarioName)

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] Simulink.data.connect start', ...
                i, n);

            dc = ...
                Simulink.data.connect(matPath);

            vars = ...
                who(dc);

            st_log(cfg, 'TRACE', ...
                '[SignalEditor %d/%d] MAT variable count=%d', ...
                i, n, numel(vars));

            if any(strcmp(vars, scenarioName))

                error( ...
                    'Scenario already exists in MAT file: %s', ...
                    scenarioName);
            end

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] rename start: %s -> %s', ...
                i, n, oldName, scenarioName);

            ok = ...
                rename( ...
                    dc, ...
                    oldName, ...
                    scenarioName);

            if ~all(ok)

                error( ...
                    'Failed to rename Signal Editor scenario: %s -> %s', ...
                    oldName, ...
                    scenarioName);
            end

            saveChanges(dc);

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] rename/saveChanges done', ...
                i, n);
        end

        set_param( ...
            sigBlock, ...
            'ActiveScenario', ...
            scenarioName);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] ActiveScenario set; save_system start', ...
            i, n);

        save_system(cfg.TopModel);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] save_system done; closing Harness', ...
            i, n);

        st_close_harness_quiet(ownerPath, harnessName);

        Status(i) = 'OK';
        Message(i) = ['SampleTime=' cfg.SignalEditorSampleTime];

        fprintf( ...
            '[%d/%d] OK   %s -> %s\n', ...
            i, n, harnessName, scenarioName);

    catch ME

        st_close_harness_quiet(ownerPath, harnessName);

        Status(i) = 'FAIL';
        Message(i) = string(ME.message);

        st_log(cfg, 'ERROR', ...
            '[SignalEditor %d/%d] %s', ...
            i, n, ME.message);

        fprintf( ...
            '[%d/%d] FAIL %s: %s\n', ...
            i, n, harnessName, ME.message);
    end

    ElapsedSec(i) = ...
        toc(timerValue);

    Timestamp(i) = ...
        string(datetime( ...
            'now', ...
            'Format', ...
            'yyyy-MM-dd HH:mm:ss'));

    st_log(cfg, 'DEBUG', ...
        '[SignalEditor %d/%d] finished | status=%s | elapsed=%.3f sec | total=%.3f sec', ...
        i, n, char(Status(i)), ElapsedSec(i), toc(totalTimer));
end

R = table( ...
    T.No, ...
    T.CUTName, ...
    T.HarnessName, ...
    SignalEditorBlock, ...
    DataFile, ...
    OldScenario, ...
    NewScenario, ...
    Status, ...
    Message, ...
    ElapsedSec, ...
    Timestamp, ...
    'VariableNames', { ...
        'No', ...
        'CUTName', ...
        'HarnessName', ...
        'SignalEditorBlock', ...
        'DataFile', ...
        'OldScenario', ...
        'NewScenario', ...
        'Status', ...
        'Message', ...
        'ElapsedSec', ...
        'Timestamp'});

st_write_result('SignalEditorResult', R);

st_log(cfg, 'INFO', ...
    'Configure Signal Editor complete | elapsed=%.3f sec', ...
    toc(totalTimer));

end


function st_close_harness_quiet(ownerPath, harnessName)

try
    sltest.harness.close(ownerPath, harnessName);
catch
end

end
