function R = st_configure_signal_editors()
%ST_CONFIGURE_SIGNAL_EDITORS Configure existing harness Signal Editor blocks.
% - OFF: preserve the legacy first-scenario rename behavior.
% - FILE/GENERATE: import SLDV test cases through Simulink.io.SLDVMatFile
%   into a dedicated Signal Editor MAT file, persist the new Filename,
%   reopen the Harness, then select the imported UT_REQ scenario.
%
% Detailed checkpoints are controlled by cfg.VerboseLogging.

cfg = st_require_runtime_target();
T = st_load_targets(cfg.OnlyEnabled);
st_force_model_stopped(cfg.TopModel);

n = height(T);
SignalEditorBlock = strings(n,1);
DataFile = strings(n,1);
OldScenario = strings(n,1);
NewScenario = strings(n,1);
ScenarioCount = zeros(n,1);
Status = strings(n,1);
Message = strings(n,1);
ElapsedSec = zeros(n,1);
Timestamp = strings(n,1);

totalTimer = tic;

st_log(cfg, 'INFO', ...
    'Configure Signal Editor start | count=%d', ...
    n);

for i = 1:n

    ownerPath = ...
        st_normalize_cut_path( ...
            T.CUTPath(i), ...
            cfg.TopModel);

    harnessName = ...
        char(T.HarnessName(i));

    profile = st_get_sldv_profile(T(i,:), cfg);
    scenarioNames = profile.ScenarioNames;
    scenarioName = scenarioNames{1};

    NewScenario(i) = ...
        string(strjoin(scenarioNames, ', '));

    ScenarioCount(i) = ...
        numel(scenarioNames);

    timerValue = tic;

    st_log(cfg, 'DEBUG', ...
        '[SignalEditor %d/%d] start | CUT=%s | Harness=%s | Scenario=%s', ...
        i, n, ownerPath, harnessName, scenarioName);

    try

        % Preserve the legacy OFF behavior. FILE/GENERATE instead use the
        % Harness ActiveScenario as their input contract and therefore do
        % not depend on direct CUT Inport blocks.
        if strcmp(profile.Mode, 'OFF')

            directInports = ...
                find_system( ...
                    ownerPath, ...
                    'SearchDepth', 1, ...
                    'Type', 'Block', ...
                    'BlockType', 'Inport');

            if isempty(directInports)

                Status(i) = 'SKIP_NO_INPORT';
                Message(i) = 'CUT has no direct Inport';
                ElapsedSec(i) = toc(timerValue);
                Timestamp(i) = string(datetime( ...
                    'now', ...
                    'Format', ...
                    'yyyy-MM-dd HH:mm:ss'));

                fprintf( ...
                    '[%d/%d] SKIP %s: no direct Inport\n', ...
                    i, n, char(T.CUTName(i)));
                continue;
            end
        end

        st_log(cfg, 'TRACE', ...
            '[SignalEditor %d/%d] force model stopped', ...
            i, n);

        st_force_model_stopped(cfg.TopModel);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] harness.load start', ...
            i, n);

        sltest.harness.load( ...
            ownerPath, ...
            harnessName);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] harness.load done', ...
            i, n);

        st_log(cfg, 'TRACE', ...
            '[SignalEditor %d/%d] locating Signal Editor block', ...
            i, n);

        sigBlock = ...
            st_find_signal_editor_block( ...
                harnessName);

        SignalEditorBlock(i) = ...
            string(sigBlock);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] block=%s', ...
            i, n, sigBlock);

        options = ...
            st_normalize_options( ...
                get_param( ...
                    sigBlock, ...
                    'options@ActiveScenario'));

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] scenario option count=%d', ...
            i, n, numel(options));

        if isempty(options)

            error( ...
                'Signal Editor has no scenario: %s', ...
                sigBlock);
        end

        oldName = ...
            options{1};

        OldScenario(i) = ...
            string(oldName);

        fileName = ...
            get_param( ...
                sigBlock, ...
                'Filename');

        matPath = ...
            st_resolve_data_file( ...
                fileName, ...
                cfg.TopModel);

        DataFile(i) = ...
            string(matPath);

        st_log(cfg, 'DEBUG', ...
            ['[SignalEditor %d/%d] data file=%s | ' ...
             'oldScenario=%s | newScenario=%s'], ...
            i, n, matPath, oldName, scenarioName);

        templateDataset = [];

        if ~strcmp(profile.Mode, 'OFF')

            % The Harness ActiveScenario is the runtime input contract.
            % It can contain upstream signals that are not direct CUT
            % Inports; those elements must survive every SLDV import.
            templateScenarioName = ...
                char(profile.HarnessScenarioName);

            if isempty(templateScenarioName)
                error( ...
                    ['SLDV profile is missing the Harness ActiveScenario. ' ...
                     'Run st_prepare_sldv_targets again.']);
            end

            templateDataset = ...
                load_scenario_dataset( ...
                    matPath, ...
                    templateScenarioName);

            assert_dataset_matches_interface( ...
                templateDataset, ...
                profile.HarnessInputNames, ...
                profile.HarnessInputTypes, ...
                profile.HarnessInputDimensions, ...
                'Harness ActiveScenario');
        end

        if strcmp(profile.Mode, 'OFF')

            set_param( ...
                sigBlock, ...
                'SampleTime', ...
                cfg.SignalEditorSampleTime);

            st_log(cfg, 'TRACE', ...
                '[SignalEditor %d/%d] SampleTime applied=%s', ...
                i, n, cfg.SignalEditorSampleTime);

            if ~strcmp(oldName, scenarioName)

                st_log(cfg, 'DEBUG', ...
                    '[SignalEditor %d/%d] Simulink.data.connect start', ...
                    i, n);

                dc = ...
                    Simulink.data.connect( ...
                        matPath);

                vars = ...
                    who(dc);

                st_log(cfg, 'TRACE', ...
                    '[SignalEditor %d/%d] MAT variable count=%d', ...
                    i, n, numel(vars));

                if any(strcmp(vars, scenarioName))

                    error( ...
                        'Scenario already exists in MAT file: %s', ...
                        scenarioName);
                end

                st_log(cfg, 'DEBUG', ...
                    '[SignalEditor %d/%d] rename start: %s -> %s', ...
                    i, n, oldName, scenarioName);

                ok = ...
                    rename( ...
                        dc, ...
                        oldName, ...
                        scenarioName);

                if ~all(ok)

                    error( ...
                        ['Failed to rename Signal Editor scenario: ' ...
                         '%s -> %s'], ...
                        oldName, ...
                        scenarioName);
                end

                saveChanges(dc);

                st_log(cfg, 'DEBUG', ...
                    '[SignalEditor %d/%d] rename/saveChanges done', ...
                    i, n);
            end

        else

            if ~same_file( ...
                    matPath, ...
                    profile.SignalEditorDataFile)

                error( ...
                    ['Signal Editor data file changed after SLDV preflight. ' ...
                     'Expected=%s, Actual=%s'], ...
                    profile.SignalEditorDataFile, ...
                    matPath);
            end

            % Close the Harness before replacing its linked MAT scenarios.
            % This avoids using a stale Signal Editor scenario cache after
            % the MAT-file content changes.
            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] closing Harness before ' ...
                 'SLDVMatFile import'], ...
                i, n);

            st_close_harness_quiet( ...
                ownerPath, ...
                harnessName);

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] Simulink.io.SLDVMatFile ' ...
                 'import start | file=%s'], ...
                i, n, profile.EffectiveDataFile);

            % GUI Signal Editor import does not merely mutate the MAT file
            % that the block is already using. After import/save, the saved
            % scenario MAT file becomes the file associated with the block.
            %
            % Reproduce that behavior explicitly:
            %   1) prepare a dedicated Signal Editor MAT file,
            %   2) write imported SLDV Dataset scenarios into that file,
            %   3) reload the Harness,
            %   4) switch the Signal Editor Filename to the prepared file,
            %   5) then select the imported ActiveScenario.
            targetMatPath = ...
                prepare_sldv_signal_editor_file( ...
                    cfg, ...
                    i, ...
                    n, ...
                    matPath);

            replace_with_sldv_scenarios( ...
                cfg, ...
                i, ...
                n, ...
                targetMatPath, ...
                scenarioNames, ...
                profile.EffectiveDataFile, ...
                profile.SourceIndices, ...
                templateDataset, ...
                profile.HarnessInputNames, ...
                profile.HarnessInputTypes, ...
                profile.HarnessInputDimensions);

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] SLDVMatFile import/save done | ' ...
                 'count=%d | targetMAT=%s'], ...
                i, n, numel(scenarioNames), targetMatPath);

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] harness.reload start', ...
                i, n);

            sltest.harness.load( ...
                ownerPath, ...
                harnessName);

            sigBlock = ...
                st_find_signal_editor_block( ...
                    harnessName);

            SignalEditorBlock(i) = ...
                string(sigBlock);

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] harness.reload done | block=%s', ...
                i, n, sigBlock);

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] switching Signal Editor Filename | ' ...
                 '%s -> %s'], ...
                i, n, matPath, targetMatPath);

            set_param( ...
                sigBlock, ...
                'Filename', ...
                targetMatPath);

            DataFile(i) = ...
                string(targetMatPath);

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] Filename switched in memory', ...
                i, n);

            % Filename-dependent dynamic parameters such as
            % options@ActiveScenario are not guaranteed to refresh in the
            % same loaded Harness immediately after set_param('Filename').
            %
            % Persist the new Filename first, close the Harness, then reopen
            % it so the Signal Editor block reconstructs its scenario list
            % from the newly associated MAT file.
            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] saving Filename change before ' ...
                 'scenario refresh'], ...
                i, n);

            save_system( ...
                cfg.TopModel);

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] closing Harness for ' ...
                 'Filename refresh'], ...
                i, n);

            st_close_harness_quiet( ...
                ownerPath, ...
                harnessName);

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] reopening Harness after Filename save', ...
                i, n);

            sltest.harness.load( ...
                ownerPath, ...
                harnessName);

            sigBlock = ...
                st_find_signal_editor_block( ...
                    harnessName);

            SignalEditorBlock(i) = ...
                string(sigBlock);

            actualFilename = ...
                st_resolve_data_file( ...
                    get_param( ...
                        sigBlock, ...
                        'Filename'), ...
                    cfg.TopModel);

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] reopened block Filename=%s | ' ...
                 'expected=%s'], ...
                i, n, actualFilename, targetMatPath);

            if ~same_file( ...
                    actualFilename, ...
                    targetMatPath)

                error( ...
                    ['Signal Editor Filename was not persisted. ' ...
                     'Expected=%s, Actual=%s'], ...
                    targetMatPath, ...
                    actualFilename);
            end

            st_log(cfg, 'TRACE', ...
                '[SignalEditor %d/%d] reading refreshed scenario options', ...
                i, n);

            refreshedOptions = ...
                st_normalize_options( ...
                    get_param( ...
                        sigBlock, ...
                        'options@ActiveScenario'));

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] refreshed scenario options=%d | ' ...
                 'names=[%s]'], ...
                i, n, numel(refreshedOptions), ...
                strjoin(refreshedOptions, ', '));

            if ~any(strcmp( ...
                    refreshedOptions, ...
                    scenarioName))

                error( ...
                    ['Imported SLDV scenario is not visible after saving ' ...
                     'and reopening the Harness with the new Signal Editor ' ...
                     'Filename. Expected=%s, Available=[%s], File=%s'], ...
                    scenarioName, ...
                    strjoin(refreshedOptions, ', '), ...
                    targetMatPath);
            end

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] switching ActiveScenario before ' ...
                 'other block parameters | %s'], ...
                i, n, scenarioName);

            set_param( ...
                sigBlock, ...
                'ActiveScenario', ...
                scenarioName);

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] ActiveScenario switched successfully', ...
                i, n);

            st_log(cfg, 'TRACE', ...
                '[SignalEditor %d/%d] applying SampleTime=%s', ...
                i, n, cfg.SignalEditorSampleTime);

            set_param( ...
                sigBlock, ...
                'SampleTime', ...
                cfg.SignalEditorSampleTime);

            st_log(cfg, 'TRACE', ...
                ['[SignalEditor %d/%d] applying ' ...
                 'OutputAfterFinalValue=Holding final value'], ...
                i, n);

            set_param( ...
                sigBlock, ...
                'OutputAfterFinalValue', ...
                'Holding final value');

            st_log(cfg, 'TRACE', ...
                ['[SignalEditor %d/%d] SampleTime=%s | ' ...
                 'OutputAfterFinalValue=Holding final value'], ...
                i, n, cfg.SignalEditorSampleTime);
        end

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] ActiveScenario set start | %s', ...
            i, n, scenarioName);

        set_param( ...
            sigBlock, ...
            'ActiveScenario', ...
            scenarioName);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] ActiveScenario set; save_system start', ...
            i, n);

        save_system( ...
            cfg.TopModel);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] save_system done; closing Harness', ...
            i, n);

        st_close_harness_quiet( ...
            ownerPath, ...
            harnessName);

        if ~strcmp(profile.Mode, 'OFF')

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] old scenario cleanup start', ...
                i, n);

            cleanup_old_scenarios( ...
                cfg, ...
                i, ...
                n, ...
                char(DataFile(i)), ...
                options, ...
                scenarioNames);

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] old scenario cleanup done', ...
                i, n);
        end

        Status(i) = 'OK';

        if strcmp(profile.Mode, 'OFF')

            Message(i) = ...
                ['SampleTime=' cfg.SignalEditorSampleTime];

        else

            Message(i) = ...
                sprintf( ...
                    ['SampleTime=%s, scenarios=%d, ' ...
                     'Reader=Simulink.io.SLDVMatFile, ' ...
                     'OutputAfterFinalValue=Holding final value'], ...
                    cfg.SignalEditorSampleTime, ...
                    numel(scenarioNames));
        end

        fprintf( ...
            '[%d/%d] OK   %s -> %s\n', ...
            i, n, harnessName, scenarioName);

    catch ME

        st_close_harness_quiet( ...
            ownerPath, ...
            harnessName);

        Status(i) = 'FAIL';
        Message(i) = string(ME.message);

        st_log(cfg, 'ERROR', ...
            '[SignalEditor %d/%d] %s', ...
            i, n, ME.message);

        st_log_exception_details( ...
            cfg, ...
            i, ...
            n, ...
            ME);

        fprintf( ...
            '[%d/%d] FAIL %s: %s\n', ...
            i, n, harnessName, ME.message);
    end

    ElapsedSec(i) = ...
        toc(timerValue);

    Timestamp(i) = ...
        string(datetime( ...
            'now', ...
            'Format', ...
            'yyyy-MM-dd HH:mm:ss'));

    st_log(cfg, 'DEBUG', ...
        ['[SignalEditor %d/%d] finished | status=%s | ' ...
         'elapsed=%.3f sec | total=%.3f sec'], ...
        i, n, char(Status(i)), ...
        ElapsedSec(i), toc(totalTimer));
end

R = table( ...
    T.No, ...
    T.CUTName, ...
    T.HarnessName, ...
    SignalEditorBlock, ...
    DataFile, ...
    OldScenario, ...
    NewScenario, ...
    ScenarioCount, ...
    Status, ...
    Message, ...
    ElapsedSec, ...
    Timestamp, ...
    'VariableNames', { ...
        'No', ...
        'CUTName', ...
        'HarnessName', ...
        'SignalEditorBlock', ...
        'DataFile', ...
        'OldScenario', ...
        'NewScenario', ...
        'ScenarioCount', ...
        'Status', ...
        'Message', ...
        'ElapsedSec', ...
        'Timestamp'});

st_write_result( ...
    'SignalEditorResult', ...
    R);

st_log(cfg, 'INFO', ...
    'Configure Signal Editor complete | elapsed=%.3f sec', ...
    toc(totalTimer));

end


function targetMatPath = prepare_sldv_signal_editor_file( ...
        cfg, ...
        targetIndex, ...
        targetCount, ...
        sourceMatPath)
%PREPARE_SLDV_SIGNAL_EDITOR_FILE
% Prepare the MAT file that will become the Signal Editor block Filename.
%
% The GUI import workflow saves imported datasets into a MAT file and
% associates that saved file with the Signal Editor block. Mirror that
% behavior rather than mutating the currently attached MAT file in place.
%
% The source MAT is copied first so the currently active scenario remains
% valid while Filename is switched. On later runs, a file already ending in
% "_sldv" is reused rather than creating "_sldv_sldv..." files.

sourceMatPath = ...
    char( ...
        java.io.File( ...
            char(sourceMatPath)).getCanonicalPath());

[sourceDir, sourceBase, sourceExt] = ...
    fileparts(sourceMatPath);

if isempty(sourceExt)
    sourceExt = '.mat';
end

suffix = '_sldv';

if length(sourceBase) >= length(suffix) && ...
        strcmpi( ...
            sourceBase(end-length(suffix)+1:end), ...
            suffix)

    targetMatPath = ...
        sourceMatPath;

    st_log(cfg, 'TRACE', ...
        '[SignalEditor %d/%d] reusing SLDV Signal Editor MAT=%s', ...
        targetIndex, targetCount, targetMatPath);

    return;
end

targetMatPath = ...
    fullfile( ...
        sourceDir, ...
        [sourceBase suffix sourceExt]);

targetMatPath = ...
    char( ...
        java.io.File( ...
            targetMatPath).getCanonicalPath());

st_log(cfg, 'DEBUG', ...
    ['[SignalEditor %d/%d] preparing dedicated Signal Editor MAT | ' ...
     'source=%s | target=%s'], ...
    targetIndex, targetCount, ...
    sourceMatPath, targetMatPath);

if ~isfile(sourceMatPath)

    error( ...
        'Source Signal Editor MAT file not found: %s', ...
        sourceMatPath);
end

copyfile( ...
    sourceMatPath, ...
    targetMatPath, ...
    'f');

if ~isfile(targetMatPath)

    error( ...
        'Failed to create dedicated Signal Editor MAT file: %s', ...
        targetMatPath);
end

end


function replace_with_sldv_scenarios( ...
        cfg, ...
        targetIndex, ...
        targetCount, ...
        matPath, ...
        newScenarioNames, ...
        dataFile, ...
        sourceIndices, ...
        templateDataset, ...
        harnessInputNames, ...
        harnessInputTypes, ...
        harnessInputDimensions)
%REPLACE_WITH_SLDV_SCENARIOS
% Import sldvData through the official Simulink.io.SLDVMatFile reader, then
% write selected TestCase Datasets into the Signal Editor MAT file.
%
% sourceIndices refers to the original SLDV TestCases order recorded during
% st_prepare_sldv_targets.

if numel(newScenarioNames) ~= numel(sourceIndices)

    error( ...
        ['SLDV Scenario/source-index count mismatch. ' ...
         'Scenarios=%d, SourceIndices=%d'], ...
        numel(newScenarioNames), ...
        numel(sourceIndices));
end

reader = ...
    Simulink.io.SLDVMatFile( ...
        dataFile);

st_log(cfg, 'TRACE', ...
    '[SignalEditor %d/%d] SLDVMatFile whos start', ...
    targetIndex, targetCount);

fileInfo = ...
    whos(reader);

st_log(cfg, 'DEBUG', ...
    '[SignalEditor %d/%d] SLDVMatFile test cases=%d', ...
    targetIndex, targetCount, numel(fileInfo));

if isempty(fileInfo)

    error( ...
        'Simulink.io.SLDVMatFile found no TestCases: %s', ...
        dataFile);
end

sourceIndices = ...
    double(sourceIndices(:));

if any(~isfinite(sourceIndices)) || ...
        any(sourceIndices < 1) || ...
        any(mod(sourceIndices, 1) ~= 0) || ...
        any(sourceIndices > numel(fileInfo))

    error( ...
        ['Invalid SLDV source indices for imported file. ' ...
         'SourceIndices=%s, AvailableTestCases=%d'], ...
        mat2str(sourceIndices.'), ...
        numel(fileInfo));
end

st_log(cfg, 'DEBUG', ...
    '[SignalEditor %d/%d] SLDVMatFile import() start', ...
    targetIndex, targetCount);

[imported, warningText] = ...
    import(reader);

st_log(cfg, 'DEBUG', ...
    '[SignalEditor %d/%d] SLDVMatFile import() returned', ...
    targetIndex, targetCount);

log_reader_warning( ...
    cfg, ...
    targetIndex, ...
    targetCount, ...
    warningText);

if ~isstruct(imported) || ...
        ~isfield(imported, 'Data')

    error( ...
        ['Unexpected Simulink.io.SLDVMatFile import result. ' ...
         'Expected a structure containing Data.']);
end

importedData = ...
    imported.Data;

if ~iscell(importedData)

    importedData = ...
        num2cell(importedData);
end

if numel(importedData) < numel(fileInfo)

    error( ...
        ['SLDVMatFile import returned fewer datasets than whos reported. ' ...
         'Imported=%d, Whos=%d'], ...
        numel(importedData), ...
        numel(fileInfo));
end

sourceNames = ...
    reader_source_names( ...
        imported, ...
        fileInfo);

datasets = ...
    cell(size(newScenarioNames));

for i = 1:numel(newScenarioNames)

    sourceIndex = ...
        sourceIndices(i);

    dataset = ...
        importedData{sourceIndex};

    if ~isa( ...
            dataset, ...
            'Simulink.SimulationData.Dataset')

        error( ...
            ['SLDVMatFile TestCase %d did not import as ' ...
             'Simulink.SimulationData.Dataset. Class=%s'], ...
            sourceIndex, ...
            class(dataset));
    end

    newName = ...
        newScenarioNames{i};

    dataset = ...
        merge_sldv_dataset_with_harness_template( ...
            dataset, ...
            templateDataset, ...
            harnessInputNames);

    assert_dataset_matches_interface( ...
        dataset, ...
        harnessInputNames, ...
        harnessInputTypes, ...
        harnessInputDimensions, ...
        sprintf('Merged SLDV TestCase %d', sourceIndex));

    dataset.Name = ...
        newName;

    datasets{i} = ...
        dataset;

    st_log(cfg, 'TRACE', ...
        ['[SignalEditor %d/%d] SLDV source #%d (%s) ' ...
         '-> scenario=%s | elements=%d'], ...
        targetIndex, ...
        targetCount, ...
        sourceIndex, ...
        sourceNames{sourceIndex}, ...
        newName, ...
        dataset.numElements);
end

st_log(cfg, 'DEBUG', ...
    '[SignalEditor %d/%d] Signal Editor MAT write start | %s', ...
    targetIndex, targetCount, matPath);

dc = ...
    Simulink.data.connect( ...
        matPath);

try

    existingVars = ...
        who(dc);

    st_log(cfg, 'TRACE', ...
        ['[SignalEditor %d/%d] target MAT existing variables=%d | ' ...
         'writing/updating scenarios=[%s]'], ...
        targetIndex, targetCount, ...
        numel(existingVars), ...
        strjoin(newScenarioNames, ', '));

    % set() updates an existing variable or creates a new one. Do not clear
    % a same-name scenario first: the Harness model may currently store that
    % scenario in ActiveScenario, and keeping it continuously present avoids
    % a temporary stale-reference window during repeated runs.
    set( ...
        dc, ...
        newScenarioNames, ...
        datasets);

    ok = ...
        saveChanges(dc);

    if ~all(ok)

        error( ...
            'Failed to save imported SLDV scenarios to Signal Editor MAT file.');
    end

    % Verify the MAT variable names explicitly. Signal Editor scenario names
    % are the scalar Dataset variable names stored in the MAT file, so the
    % imported SLDV TestCase names must have been rewritten to the UT_REQ
    % names before the block is re-associated with this file.
    savedVars = ...
        who(dc);

    missingScenarioNames = ...
        newScenarioNames( ...
            ~ismember( ...
                newScenarioNames, ...
                savedVars));

    st_log(cfg, 'DEBUG', ...
        ['[SignalEditor %d/%d] target MAT scenario variables | ' ...
         'expected=[%s] | actual=[%s]'], ...
        targetIndex, targetCount, ...
        strjoin(newScenarioNames, ', '), ...
        strjoin(savedVars, ', '));

    if ~isempty(missingScenarioNames)

        error( ...
            ['Imported SLDV scenario variable rename/save failed. ' ...
             'Missing=[%s], File=%s'], ...
            strjoin(missingScenarioNames, ', '), ...
            matPath);
    end

catch ME

    try
        discardChanges(dc);
    catch
    end

    rethrow(ME);
end

st_log(cfg, 'DEBUG', ...
    '[SignalEditor %d/%d] Signal Editor MAT write done', ...
    targetIndex, targetCount);

end


function dataset = load_scenario_dataset(matPath, scenarioName)
%LOAD_SCENARIO_DATASET Load one named Signal Editor scenario Dataset.

loaded = load(matPath, scenarioName);

if ~isfield(loaded, scenarioName)
    error( ...
        'Signal Editor scenario is missing from MAT file: %s', ...
        scenarioName);
end

dataset = loaded.(scenarioName);

if ~isa(dataset, 'Simulink.SimulationData.Dataset') || ...
        dataset.numElements == 0
    error( ...
        ['Signal Editor scenario must be a nonempty ' ...
         'Simulink.SimulationData.Dataset: %s'], ...
        scenarioName);
end

end


function merged = merge_sldv_dataset_with_harness_template( ...
        sldvDataset, ...
        templateDataset, ...
        harnessInputNames)
%MERGE_SLDV_DATASET_WITH_HARNESS_TEMPLATE
% Build a Dataset in Harness input order. SLDV-provided elements replace
% matching template elements; every omitted external Harness input remains
% unchanged from the template scenario.

if ~isa(templateDataset, 'Simulink.SimulationData.Dataset') || ...
        templateDataset.numElements == 0
    error('Harness input template Dataset is empty or invalid.');
end

templateNames = dataset_element_names(templateDataset);
sldvNames = dataset_element_names(sldvDataset);
expectedNames = cellstr(string(harnessInputNames(:)));

if ~isequal(string(templateNames(:)), string(expectedNames(:)))
    error( ...
        ['Harness input template no longer matches the prepared SLDV ' ...
         'profile. Template=[%s], Expected=[%s]'], ...
        strjoin(templateNames, ', '), ...
        strjoin(expectedNames, ', '));
end

unexpected = ...
    sldvNames(~ismember(string(sldvNames), string(templateNames)));

if ~isempty(unexpected)
    error( ...
        ['SLDV Dataset contains signals that are not present in the ' ...
         'Harness input template: [%s]'], ...
        strjoin(unexpected, ', '));
end

merged = Simulink.SimulationData.Dataset;

for templateIndex = 1:numel(templateNames)
    name = templateNames{templateIndex};
    sldvIndex = find(strcmp(sldvNames, name), 1, 'first');

    if isempty(sldvIndex)
        element = templateDataset.getElement(templateIndex);
    else
        element = sldvDataset.getElement(sldvIndex);
    end

    merged = addElement(merged, element);
end

end


function assert_dataset_matches_interface( ...
        dataset, ...
        expectedNames, ...
        expectedTypes, ...
        expectedDimensions, ...
        label)
%ASSERT_DATASET_MATCHES_INTERFACE Validate names, order, types and dims.

actualNames = dataset_element_names(dataset);
expectedNames = cellstr(string(expectedNames(:)));

if ~isequal(string(actualNames(:)), string(expectedNames(:)))
    error( ...
        '%s input names/order mismatch. Actual=[%s], Expected=[%s]', ...
        label, ...
        strjoin(actualNames, ', '), ...
        strjoin(expectedNames, ', '));
end

for i = 1:numel(expectedNames)
    element = dataset.getElement(i);
    [actualType, actualDimensions] = element_value_signature(element);

    if ~strcmpi(actualType, expectedTypes{i})
        error( ...
            '%s data type mismatch at input %d (%s). Actual=%s, Expected=%s', ...
            label, i, expectedNames{i}, actualType, expectedTypes{i});
    end

    if ~isequal(actualDimensions, expectedDimensions{i})
        error( ...
            '%s dimensions mismatch at input %d (%s). Actual=%s, Expected=%s', ...
            label, i, expectedNames{i}, ...
            mat2str(actualDimensions), mat2str(expectedDimensions{i}));
    end
end

end


function names = dataset_element_names(dataset)

names = cell(dataset.numElements, 1);

for i = 1:dataset.numElements
    element = dataset.getElement(i);
    names{i} = strtrim(char(string(element.Name)));
    if isempty(names{i})
        error('Dataset element %d has an empty Name.', i);
    end
end

if numel(unique(string(names))) ~= numel(names)
    error('Dataset contains duplicate element names: [%s]', ...
        strjoin(names, ', '));
end

end


function [dataType, dimensions] = element_value_signature(element)

value = element;
if isa(element, 'Simulink.SimulationData.Signal')
    value = element.Values;
end

if isa(value, 'timeseries')
    data = value.Data;
    dims = size(data);

    if ~isempty(value.Time) && ...
            isprop(value, 'IsTimeFirst') && ...
            value.IsTimeFirst && ...
            ~isempty(dims)
        dims = dims(2:end);
    elseif ~isempty(value.Time) && ~isempty(dims) && ...
            dims(end) == numel(value.Time)
        dims = dims(1:end-1);
    elseif ~isempty(value.Time) && ~isempty(dims) && ...
            dims(1) == numel(value.Time)
        dims = dims(2:end);
    end

elseif istimetable(value)
    data = value.Variables;
    dims = size(data);
    dims = dims(2:end);

else
    data = value;
    dims = size(value);
end

if isa(data, 'embedded.fi')
    dataType = 'fixed';
elseif isstruct(data)
    dataType = 'bus';
else
    dataType = class(data);
end

dimensions = double(dims(:).');
if isempty(dimensions) || all(dimensions == 1)
    dimensions = 1;
end

end


function cleanup_old_scenarios( ...
        cfg, ...
        targetIndex, ...
        targetCount, ...
        matPath, ...
        oldScenarioNames, ...
        newScenarioNames)
%CLEANUP_OLD_SCENARIOS
% Remove obsolete scenarios only after the Harness ActiveScenario has been
% switched to a new imported SLDV scenario and the model has been saved.

obsolete = ...
    oldScenarioNames( ...
        ~ismember( ...
            oldScenarioNames, ...
            newScenarioNames));

if isempty(obsolete)

    st_log(cfg, 'TRACE', ...
        '[SignalEditor %d/%d] no obsolete scenarios to remove', ...
        targetIndex, targetCount);

    return;
end

dc = ...
    Simulink.data.connect( ...
        matPath);

try

    existingVars = ...
        who(dc);

    removable = ...
        obsolete( ...
            ismember( ...
                obsolete, ...
                existingVars));

    if isempty(removable)

        st_log(cfg, 'TRACE', ...
            '[SignalEditor %d/%d] obsolete scenarios already absent', ...
            targetIndex, targetCount);

        return;
    end

    st_log(cfg, 'TRACE', ...
        '[SignalEditor %d/%d] removing obsolete scenarios=[%s]', ...
        targetIndex, targetCount, ...
        strjoin(removable, ', '));

    clear( ...
        dc, ...
        removable);

    ok = ...
        saveChanges(dc);

    if ~all(ok)

        error( ...
            'Failed to remove obsolete Signal Editor scenarios.');
    end

catch ME

    try
        discardChanges(dc);
    catch
    end

    rethrow(ME);
end

end


function st_log_exception_details( ...
        cfg, ...
        targetIndex, ...
        targetCount, ...
        ME)

if ~isempty(ME.identifier)

    st_log(cfg, 'ERROR', ...
        '[SignalEditor %d/%d] Identifier=%s', ...
        targetIndex, targetCount, ME.identifier);
end

if ~isempty(ME.stack)

    top = ...
        ME.stack(1);

    st_log(cfg, 'ERROR', ...
        '[SignalEditor %d/%d] Stack=%s:%d', ...
        targetIndex, targetCount, ...
        top.name, top.line);
end

for causeIndex = 1:numel(ME.cause)

    cause = ...
        ME.cause{causeIndex};

    st_log(cfg, 'ERROR', ...
        '[SignalEditor %d/%d] Cause #%d: %s', ...
        targetIndex, targetCount, ...
        causeIndex, cause.message);
end

end


function sourceNames = reader_source_names(imported, fileInfo)

sourceNames = ...
    cell(numel(fileInfo),1);

for i = 1:numel(fileInfo)

    try
        sourceNames{i} = ...
            char(fileInfo(i).name);
    catch
        sourceNames{i} = ...
            sprintf( ...
                'SLDV TestCase %d', ...
                i);
    end
end

% Different FileType documentation pages historically used Name/Names.
% Use either when provided, but do not depend on them for indexing.
if isfield(imported, 'Name')

    names = ...
        imported.Name;

elseif isfield(imported, 'Names')

    names = ...
        imported.Names;

else

    return;
end

if ischar(names)

    names = ...
        {names};

elseif isstring(names)

    names = ...
        cellstr(names(:));
end

if iscell(names) && ...
        numel(names) == numel(sourceNames)

    for i = 1:numel(names)

        if ~isempty(names{i})

            sourceNames{i} = ...
                char(string(names{i}));
        end
    end
end

end


function log_reader_warning( ...
        cfg, ...
        targetIndex, ...
        targetCount, ...
        warningText)

if isempty(warningText)
    return;
end

if iscell(warningText)

    warningText = ...
        strjoin( ...
            string(warningText(:)), ...
            ' | ');

else

    warningText = ...
        string(warningText);
end

warningText = ...
    strtrim(warningText);

if strlength(warningText) == 0
    return;
end

st_log(cfg, 'WARN', ...
    '[SignalEditor %d/%d] SLDVMatFile import warning: %s', ...
    targetIndex, ...
    targetCount, ...
    char(warningText));

end


function tf = same_file(a, b)

a = ...
    char( ...
        java.io.File( ...
            char(a)).getCanonicalPath());

b = ...
    char( ...
        java.io.File( ...
            char(b)).getCanonicalPath());

if ispc
    tf = strcmpi(a, b);
else
    tf = strcmp(a, b);
end

end


function st_close_harness_quiet(ownerPath, harnessName)

try
    sltest.harness.close( ...
        ownerPath, ...
        harnessName);
catch
end

end
