function R = st_configure_assessments()
%ST_CONFIGURE_ASSESSMENTS
% Existing Harness의 Test Assessment를 자동 구성합니다.
%
% Verify 대상:
%
% cfg.VerifyHarnessOutportsOnly == true
%   Test Assessment Input은 다음 순서로 생성된다고 가정합니다.
%
%   1) Signal Editor ActiveScenario 변수
%   2) Harness 최상위 Outport 신호
%
%   따라서 Scenario 변수 개수 K를 건너뛴 뒤,
%   Assessment Port K+1부터 Harness Outport 순서로 verify 대상을 선택합니다.
%
%   Signal 이름 자체는 매칭 기준으로 사용하지 않습니다.
%
% cfg.VerifyHarnessOutportsOnly == false
%   Test Assessment의 모든 Input Data Symbol
%
%
% Bus 배열:
%
% cfg.VerifyFirstBusElementOnly == true
%   Bus 배열에서는 첫 번째 Bus 요소만 verify
%
% cfg.VerifyFirstBusElementOnly == false
%   Bus 배열 전체를 verify
%
%
% Verify 시점:
%
% cfg.VerifyAtSampleTimeOnly == false
%   step1 --true--> step2
%
% cfg.VerifyAtSampleTimeOnly == true
%   step1 --after(ExpectedValueSampleTime, sec)--> step2
%
%
% Expected value:
%   초기 생성값은 0
%   AutoUpdateExpectedOnFail 옵션은 Test 실행 후 별도 처리

cfg = st_require_runtime_target();

T = st_load_targets( ...
    cfg.OnlyEnabled);


st_force_model_stopped( ...
    cfg.TopModel);


n = height(T);


if n == 0

    warning( ...
        '처리할 CUT가 없습니다.');

    R = table();

    return;
end


%% ============================================================
% Transition condition
%% ============================================================

if cfg.VerifyAtSampleTimeOnly

    legacyTransitionCondition = ...
        sprintf( ...
            'after(%.17g, sec)', ...
            cfg.ExpectedValueSampleTime);

    stopTime = ...
        str2double( ...
            cfg.HarnessStopTime);

    if isfinite(stopTime) && ...
            stopTime <= cfg.ExpectedValueSampleTime

        warning( ...
            ['VerifyAtSampleTimeOnly=true인데 HarnessStopTime이 ' ...
             'ExpectedValueSampleTime 이하입니다. ' ...
             '안정적인 평가를 위해 StopTime을 SampleTime보다 크게 두는 것을 권장합니다.']);
    end

else

    legacyTransitionCondition = ...
        'true';
end


%% ============================================================
% 결과 변수
%% ============================================================

CUTPath = strings(n,1);
AssessmentBlock = strings(n,1);
ScenarioName = strings(n,1);
VerifyMode = strings(n,1);
BusArrayMode = strings(n,1);
TransitionCondition = strings(n,1);
AssessmentInputCount = zeros(n,1);
ScenarioInputCount = zeros(n,1);
HarnessOutportCount = zeros(n,1);
HarnessOutputSignalCount = zeros(n,1);
VerifyTargetCount = zeros(n,1);
VerifyCount = zeros(n,1);
ElapsedSec = zeros(n,1);
Status = strings(n,1);
Message = strings(n,1);
Timestamp = strings(n,1);


fprintf('\n');
fprintf('============================================\n');
fprintf('Configure Test Assessment\n');
fprintf('============================================\n');

totalTimer = tic;

st_log(cfg, 'INFO', ...
    'Configure Test Assessment start | count=%d', ...
    n);


%% ============================================================
% CUT 반복
%% ============================================================

for i = 1:n

    ownerPath = ...
        st_normalize_cut_path( ...
            T.CUTPath(i), ...
            cfg.TopModel);

    harnessName = ...
        char(T.HarnessName(i));

    cutName = ...
        char(T.CUTName(i));

    profile = st_get_sldv_profile(T(i,:), cfg);
    scenarioNames = profile.ScenarioNames;
    scenarioName = scenarioNames{1};

    if strcmp(profile.Mode, 'OFF')
        transitionCondition = legacyTransitionCondition;
    else
        transitionCondition = sprintf('after(%.17g, sec)', profile.Tmax);
    end


    CUTPath(i) = ...
        string(ownerPath);

    ScenarioName(i) = ...
        string(strjoin(scenarioNames, ', '));

    TransitionCondition(i) = ...
        string(transitionCondition);


    if cfg.VerifyHarnessOutportsOnly

        VerifyMode(i) = ...
            'SCENARIO_OFFSET_HARNESS_OUTPORTS';

    else

        VerifyMode(i) = ...
            'ALL_ASSESSMENT_INPUTS';
    end


    if cfg.VerifyFirstBusElementOnly

        BusArrayMode(i) = ...
            'FIRST_ELEMENT_ONLY';

    else

        BusArrayMode(i) = ...
            'ALL_ELEMENTS';
    end


    timerValue = tic;

    st_log(cfg, 'DEBUG', ...
        '[Assessment %d/%d] start | CUT=%s | Harness=%s | Scenario=%s', ...
        i, n, ownerPath, harnessName, scenarioName);

    fprintf('\n');
    fprintf('[%d/%d] %s\n', ...
        i, ...
        n, ...
        cutName);

    fprintf('  CUT        : %s\n', ...
        ownerPath);

    fprintf('  Harness    : %s\n', ...
        harnessName);

    fprintf('  Scenario   : %s\n', ...
        scenarioName);

    fprintf('  Transition : %s\n', ...
        transitionCondition);


    try

        %% ====================================================
        % Model 상태 정리
        %% ====================================================

        st_log(cfg, 'TRACE', ...
            '[Assessment %d/%d] force model stopped', ...
            i, n);

        st_force_model_stopped( ...
            cfg.TopModel);

        st_log(cfg, 'TRACE', ...
            '[Assessment %d/%d] model stopped', ...
            i, n);


        %% ====================================================
        % Harness Load
        %% ====================================================

        st_log(cfg, 'DEBUG', ...
            '[Assessment %d/%d] harness.load start', ...
            i, n);

        sltest.harness.load( ...
            ownerPath, ...
            harnessName);

        st_log(cfg, 'DEBUG', ...
            '[Assessment %d/%d] harness.load done', ...
            i, n);


        %% ====================================================
        % Test Assessment 찾기
        %% ====================================================

        assess = ...
            st_find_assessment_block( ...
                harnessName);

        AssessmentBlock(i) = ...
            string(assess);

        st_log(cfg, 'DEBUG', ...
            '[Assessment %d/%d] Assessment block=%s', ...
            i, n, assess);


        %% ====================================================
        % Assessment Input Symbol 정보
        %% ====================================================

        assessmentSpecs = ...
            st_collect_assessment_input_specs( ...
                assess);

        AssessmentInputCount(i) = ...
            height(assessmentSpecs);

        st_log(cfg, 'DEBUG', ...
            '[Assessment %d/%d] Assessment input count=%d | symbols=[%s]', ...
            i, n, ...
            height(assessmentSpecs), ...
            strjoin(cellstr(assessmentSpecs.Name), ', '));


        %% ====================================================
        % Verify 대상 결정
        %% ====================================================

        if cfg.VerifyHarnessOutportsOnly

            % Assessment input order was confirmed as:
            %   Signal Editor ActiveScenario variables
            %   -> Harness output signals
            %
            % Do NOT infer Scenario count from CUT direct Inport blocks.
            % Some Harnesses expose Scenario variables even when the CUT
            % itself has no direct Inport block detected by find_system.
            scenarioNames = ...
                st_collect_signal_editor_scenario_names( ...
                    harnessName, ...
                    cfg.TopModel);

            scenarioInputCount = ...
                numel(scenarioNames);

            ScenarioInputCount(i) = ...
                scenarioInputCount;

            st_log(cfg, 'DEBUG', ...
                '[Assessment %d/%d] Scenario input count=%d | names=[%s]', ...
                i, n, ...
                scenarioInputCount, ...
                strjoin(cellstr(scenarioNames), ', '));


            harnessOutputs = ...
                st_collect_harness_output_signals( ...
                    harnessName);

            HarnessOutportCount(i) = ...
                height(harnessOutputs);

            st_log(cfg, 'DEBUG', ...
                '[Assessment %d/%d] Harness Outport rows=%d', ...
                i, n, height(harnessOutputs));

            usableHarnessOutputs = ...
                harnessOutputs( ...
                    strlength(harnessOutputs.SignalName) > 0, ...
                    :);

            HarnessOutputSignalCount(i) = ...
                height(usableHarnessOutputs);

            st_log(cfg, 'DEBUG', ...
                '[Assessment %d/%d] usable Harness outputs=%d | names=[%s]', ...
                i, n, ...
                height(usableHarnessOutputs), ...
                strjoin(cellstr(usableHarnessOutputs.SignalName), ', '));


            st_log(cfg, 'DEBUG', ...
                '[Assessment %d/%d] output target selection start', ...
                i, n);

            targets = ...
                select_harness_output_targets( ...
                    assessmentSpecs, ...
                    usableHarnessOutputs, ...
                    scenarioInputCount);

            st_log(cfg, 'DEBUG', ...
                '[Assessment %d/%d] output target selection done | count=%d', ...
                i, n, height(targets));

            for logIdx = 1:height(targets)

                st_log(cfg, 'TRACE', ...
                    ['[Assessment %d/%d] map #%d | AssessmentPort=%d | ' ...
                     'AssessmentSymbol=%s | HarnessPort=%d | HarnessSignal=%s'], ...
                    i, n, logIdx, ...
                    double(targets.Port(logIdx)), ...
                    char(targets.Name(logIdx)), ...
                    double(targets.HarnessOutportPort(logIdx)), ...
                    char(targets.HarnessSignalName(logIdx)));
            end


            if height(usableHarnessOutputs) > 0 && ...
                    isempty(targets)

                error( ...
                    ['Scenario offset 적용 후 Harness Outport에 대응하는 ' ...
                     'Test Assessment Input Symbol을 찾지 못했습니다.']);
            end

        else

            targets = ...
                assessmentSpecs;

            ScenarioInputCount(i) = ...
                0;

            HarnessOutportCount(i) = ...
                0;

            HarnessOutputSignalCount(i) = ...
                0;
        end


        VerifyTargetCount(i) = ...
            height(targets);


        %% ====================================================
        % Verify Action 생성
        %% ====================================================

        st_log(cfg, 'DEBUG', ...
            '[Assessment %d/%d] build verify action start | targets=%d', ...
            i, n, height(targets));

        [verifyAction, verifyCount] = ...
            st_build_verify_action( ...
                targets, ...
                cfg.TopModel, ...
                cfg.VerifyFirstBusElementOnly);

        VerifyCount(i) = ...
            verifyCount;

        st_log(cfg, 'DEBUG', ...
            '[Assessment %d/%d] build verify action done | verify lines=%d', ...
            i, n, verifyCount);


        %% ====================================================
        % Assessment Scenario 구성
        %% ====================================================

        st_log(cfg, 'DEBUG', ...
            '[Assessment %d/%d] prepare Assessment scenario start', ...
            i, n);

        st_prepare_assessment_scenario( ...
            assess, ...
            scenarioNames, ...
            verifyAction, ...
            transitionCondition);

        st_log(cfg, 'DEBUG', ...
            '[Assessment %d/%d] prepare Assessment scenario done', ...
            i, n);


        %% ====================================================
        % 저장
        %% ====================================================

        st_log(cfg, 'DEBUG', ...
            '[Assessment %d/%d] save_system start', ...
            i, n);

        save_system( ...
            cfg.TopModel);

        st_log(cfg, 'DEBUG', ...
            '[Assessment %d/%d] save_system done; closing Harness', ...
            i, n);


        st_close_harness_quiet( ...
            ownerPath, ...
            harnessName);


        Status(i) = ...
            'OK';

        Message(i) = ...
            sprintf( ...
                ['assessment=%d, ' ...
                 'scenarioInputs=%d, scenarios=%d, ' ...
                 'outSignals=%d, ' ...
                 'targets=%d, ' ...
                 'verify=%d'], ...
                AssessmentInputCount(i), ...
                ScenarioInputCount(i), ...
                numel(scenarioNames), ...
                HarnessOutputSignalCount(i), ...
                height(targets), ...
                verifyCount);


        fprintf( ...
            ['  -> OK : ' ...
             'assessment=%d, ' ...
             'scenarioInputs=%d, scenarios=%d, ' ...
             'outSignals=%d, ' ...
             'targets=%d, ' ...
             'verify=%d\n'], ...
            AssessmentInputCount(i), ...
            ScenarioInputCount(i), ...
            numel(scenarioNames), ...
            HarnessOutputSignalCount(i), ...
            height(targets), ...
            verifyCount);


    catch ME

        st_close_harness_quiet( ...
            ownerPath, ...
            harnessName);

        Status(i) = ...
            'FAIL';

        Message(i) = ...
            string(ME.message);

        fprintf( ...
            '  -> FAIL : %s\n', ...
            ME.message);
    end


    ElapsedSec(i) = ...
        toc(timerValue);

    st_log(cfg, 'DEBUG', ...
        '[Assessment %d/%d] finished | status=%s | elapsed=%.3f sec | total=%.3f sec', ...
        i, n, char(Status(i)), ElapsedSec(i), toc(totalTimer));

    Timestamp(i) = ...
        string( ...
            datetime( ...
                'now', ...
                'Format', ...
                'yyyy-MM-dd HH:mm:ss'));
end


%% ============================================================
% Top Model 저장
%% ============================================================

try

    save_system( ...
        cfg.TopModel);

catch ME

    warning( ...
        'Top Model 저장 중 오류: %s', ...
        ME.message);
end


%% ============================================================
% 결과 Table
%% ============================================================

R = table( ...
    T.No, ...
    T.CUTName, ...
    CUTPath, ...
    T.HarnessName, ...
    AssessmentBlock, ...
    ScenarioName, ...
    VerifyMode, ...
    BusArrayMode, ...
    TransitionCondition, ...
    AssessmentInputCount, ...
    ScenarioInputCount, ...
    HarnessOutportCount, ...
    HarnessOutputSignalCount, ...
    VerifyTargetCount, ...
    VerifyCount, ...
    ElapsedSec, ...
    Status, ...
    Message, ...
    Timestamp, ...
    'VariableNames', { ...
        'No', ...
        'CUTName', ...
        'CUTPath', ...
        'HarnessName', ...
        'AssessmentBlock', ...
        'ScenarioName', ...
        'VerifyMode', ...
        'BusArrayMode', ...
        'TransitionCondition', ...
        'AssessmentInputCount', ...
        'ScenarioInputCount', ...
        'HarnessOutportCount', ...
        'HarnessOutputSignalCount', ...
        'VerifyTargetCount', ...
        'VerifyCount', ...
        'ElapsedSec', ...
        'Status', ...
        'Message', ...
        'Timestamp'});


st_write_result( ...
    'AssessmentResult', ...
    R);


fprintf('\n');
fprintf('============================================\n');
fprintf('Test Assessment Result\n');
fprintf('============================================\n');
fprintf('OK   : %d\n', ...
    sum(strcmp(Status, 'OK')));
fprintf('FAIL : %d\n', ...
    sum(strcmp(Status, 'FAIL')));
fprintf('Total: %d\n', ...
    n);
fprintf('============================================\n');

st_log(cfg, 'INFO', ...
    'Configure Test Assessment complete | elapsed=%.3f sec', ...
    toc(totalTimer));

end


%% ============================================================
% Harness Outport <-> Assessment Input Matching
%% ============================================================

function targets = ...
    select_harness_output_targets( ...
        assessmentSpecs, ...
        harnessOutputs, ...
        scenarioInputCount)
% Matching rule confirmed by Harness inspection:
%
%   Assessment Input Port order
%       = Signal Editor scenario variables first
%       + Harness output signals second
%
% If scenarioInputCount == K:
%   Assessment rows 1..K       -> input scenario
%   Assessment rows K+1..end   -> Harness outputs in Harness Outport order
%
% Signal names are diagnostic metadata only.
% No slash deletion, makeValidName, or text normalization is used.

if isempty(assessmentSpecs)

    if ~isempty(harnessOutputs)
        error( ...
            ['Assessment Input Symbol이 없지만 Harness output signal이 ' ...
             '%d개 존재합니다.'], ...
            height(harnessOutputs));
    end

    targets = ...
        assessmentSpecs([],:);

    return;
end


if ~ismember( ...
        'Port', ...
        assessmentSpecs.Properties.VariableNames)

    error( ...
        ['Assessment input specs에 Port 열이 없습니다. ' ...
         'st_collect_assessment_input_specs.m을 최신 패치로 교체하세요.']);
end


scenarioInputCount = ...
    double(scenarioInputCount);

if ~isscalar(scenarioInputCount) || ...
        ~isfinite(scenarioInputCount) || ...
        scenarioInputCount < 0 || ...
        mod(scenarioInputCount,1) ~= 0

    error( ...
        'Invalid scenario input count: %g', ...
        scenarioInputCount);
end


nAssessment = ...
    height(assessmentSpecs);

nHarness = ...
    height(harnessOutputs);

expectedAssessmentCount = ...
    scenarioInputCount + nHarness;


%% ============================================================
% Assessment Port sequence validation
%% ============================================================

expectedPorts = ...
    (1:nAssessment).';

actualPorts = ...
    double(assessmentSpecs.Port);

if ~isequal( ...
        actualPorts, ...
        expectedPorts)

    error( ...
        ['Assessment Input Port가 연속된 1..N 순서가 아닙니다. ' ...
         'Actual=%s'], ...
        mat2str(actualPorts.'));
end


%% ============================================================
% Count validation
%% ============================================================

if nAssessment ~= expectedAssessmentCount

    assessmentNames = ...
        strjoin( ...
            cellstr(assessmentSpecs.Name), ...
            ', ');

    harnessNames = ...
        strjoin( ...
            cellstr(harnessOutputs.SignalName), ...
            ', ');

    error( ...
        ['Assessment 입력 개수가 예상 순서와 맞지 않습니다. ' ...
         'Assessment=%d, Scenario=%d, HarnessOutput=%d, Expected=%d. ' ...
         'AssessmentSymbols=[%s], HarnessOutputs=[%s]'], ...
        nAssessment, ...
        scenarioInputCount, ...
        nHarness, ...
        expectedAssessmentCount, ...
        assessmentNames, ...
        harnessNames);
end


%% ============================================================
% Skip scenario area and take output area
%% ============================================================

if nHarness == 0

    targets = ...
        assessmentSpecs([],:);

    return;
end

firstOutputRow = ...
    scenarioInputCount + 1;

lastOutputRow = ...
    scenarioInputCount + nHarness;

targetRows = ...
    (firstOutputRow:lastOutputRow).';

targets = ...
    assessmentSpecs(targetRows,:);


%% ============================================================
% Diagnostic metadata
%% ============================================================

targets.MatchMode = ...
    repmat( ...
        string('SCENARIO_OFFSET_PORT_ORDER'), ...
        nHarness, ...
        1);

targets.ScenarioInputCount = ...
    repmat( ...
        scenarioInputCount, ...
        nHarness, ...
        1);

targets.HarnessOutportPort = ...
    harnessOutputs.Port;

targets.HarnessSignalName = ...
    harnessOutputs.SignalName;

targets.HarnessOutportBlock = ...
    harnessOutputs.OutportBlock;

end


%% ============================================================
% Harness Close
%% ============================================================

function st_close_harness_quiet( ...
        ownerPath, ...
        harnessName)

try

    sltest.harness.close( ...
        ownerPath, ...
        harnessName);

catch
end

end
