function R = st_configure_harnesses()
%ST_CONFIGURE_HARNESSES Set StopTime on existing harnesses.
%
% Detailed checkpoints are controlled by cfg.VerboseLogging.

cfg = st_require_runtime_target();
T = st_load_targets(cfg.OnlyEnabled);
st_force_model_stopped(cfg.TopModel);

n = height(T);
Status = strings(n,1);
Message = strings(n,1);
StopTime = strings(n,1);
ElapsedSec = zeros(n,1);
Timestamp = strings(n,1);

totalTimer = tic;

st_log(cfg, 'INFO', ...
    'Configure Harnesses start | count=%d | StopTime=%s', ...
    n, ...
    cfg.HarnessStopTime);

for i = 1:n

    ownerPath = ...
        st_normalize_cut_path( ...
            T.CUTPath(i), ...
            cfg.TopModel);

    harnessName = ...
        char(T.HarnessName(i));

    timerValue = tic;

    profile = st_get_sldv_profile(T(i,:), cfg);
    if strcmp(profile.Mode, 'OFF')
        targetStopTime = cfg.HarnessStopTime;
    else
        targetStopTime = sprintf('%.17g', profile.Tmax);
    end
    StopTime(i) = string(targetStopTime);

    st_log(cfg, 'DEBUG', ...
        '[HarnessConfig %d/%d] start | CUT=%s | Harness=%s', ...
        i, n, ownerPath, harnessName);

    try

        st_log(cfg, 'TRACE', ...
            '[HarnessConfig %d/%d] force model stopped', ...
            i, n);

        st_force_model_stopped(cfg.TopModel);

        st_log(cfg, 'DEBUG', ...
            '[HarnessConfig %d/%d] harness.load start', ...
            i, n);

        sltest.harness.load(ownerPath, harnessName);

        st_log(cfg, 'DEBUG', ...
            '[HarnessConfig %d/%d] harness.load done', ...
            i, n);

        st_log(cfg, 'TRACE', ...
            '[HarnessConfig %d/%d] set StopTime=%s', ...
            i, n, targetStopTime);

        set_param( ...
            harnessName, ...
            'StopTime', ...
            targetStopTime);

        st_log(cfg, 'DEBUG', ...
            '[HarnessConfig %d/%d] save_system start', ...
            i, n);

        save_system(cfg.TopModel);

        st_log(cfg, 'DEBUG', ...
            '[HarnessConfig %d/%d] save_system done; closing Harness', ...
            i, n);

        st_close_harness_quiet(ownerPath, harnessName);

        Status(i) = 'OK';
        Message(i) = ['StopTime=' targetStopTime];

        fprintf( ...
            '[%d/%d] OK   %s StopTime=%s\n', ...
            i, n, harnessName, targetStopTime);

    catch ME

        st_close_harness_quiet(ownerPath, harnessName);

        Status(i) = 'FAIL';
        Message(i) = string(ME.message);

        st_log(cfg, 'ERROR', ...
            '[HarnessConfig %d/%d] %s', ...
            i, n, ME.message);

        fprintf( ...
            '[%d/%d] FAIL %s: %s\n', ...
            i, n, harnessName, ME.message);
    end

    ElapsedSec(i) = toc(timerValue);

    Timestamp(i) = ...
        string(datetime( ...
            'now', ...
            'Format', ...
            'yyyy-MM-dd HH:mm:ss'));

    st_log(cfg, 'DEBUG', ...
        '[HarnessConfig %d/%d] finished | status=%s | elapsed=%.3f sec | total=%.3f sec', ...
        i, n, char(Status(i)), ElapsedSec(i), toc(totalTimer));
end

R = table( ...
    T.No, ...
    T.CUTName, ...
    T.HarnessName, ...
    StopTime, ...
    Status, ...
    Message, ...
    ElapsedSec, ...
    Timestamp, ...
    'VariableNames', { ...
        'No', ...
        'CUTName', ...
        'HarnessName', ...
        'StopTime', ...
        'Status', ...
        'Message', ...
        'ElapsedSec', ...
        'Timestamp'});

st_write_result('HarnessConfigResult', R);

st_log(cfg, 'INFO', ...
    'Configure Harnesses complete | elapsed=%.3f sec', ...
    toc(totalTimer));

end


function st_close_harness_quiet(ownerPath, harnessName)

try
    sltest.harness.close(ownerPath, harnessName);
catch
end

end
