function R = st_create_harnesses()
%ST_CREATE_HARNESSES Create missing Harnesses from TestManagement.xlsx.
%
% Existing Harnesses are skipped.
% Harness creation uses normal compile mode.

cfg = st_require_runtime_target();

T = st_load_targets( ...
    cfg.OnlyEnabled);

n = height(T);

Status = strings(n,1);
Message = strings(n,1);
ElapsedSec = zeros(n,1);
Timestamp = strings(n,1);


fprintf('\n');
fprintf('============================================\n');
fprintf('Create Test Harnesses\n');
fprintf('Model : %s\n', cfg.TopModel);
fprintf('Count : %d\n', n);
fprintf('============================================\n');


for i = 1:n

    cutName = ...
        char(T.CUTName(i));

    ownerPath = ...
        st_normalize_cut_path( ...
            T.CUTPath(i), ...
            cfg.TopModel);

    harnessName = ...
        char(T.HarnessName(i));

    fprintf('\n[%d/%d] %s\n', ...
        i, ...
        n, ...
        cutName);

    fprintf('  CUT     : %s\n', ownerPath);
    fprintf('  Harness : %s\n', harnessName);

    timerValue = tic;


    try

        blockHandle = ...
            getSimulinkBlockHandle( ...
                ownerPath);

        if blockHandle == -1

            error( ...
                'CUT not found: %s', ...
                ownerPath);
        end

        if ~strcmp( ...
                get_param(blockHandle, 'BlockType'), ...
                'SubSystem')

            error( ...
                'CUT is not a Subsystem: %s', ...
                ownerPath);
        end


        existing = ...
            sltest.harness.find( ...
                ownerPath, ...
                'SearchDepth', 0, ...
                'Name', harnessName);

        if ~isempty(existing)

            Status(i) = 'SKIP';
            Message(i) = 'Harness already exists';

            fprintf('  -> SKIP : already exists\n');

        else

            st_force_model_stopped( ...
                cfg.TopModel);


            sltest.harness.create( ...
                ownerPath, ...
                'Name', harnessName, ...
                'Source', 'Signal Editor', ...
                'Sink', 'Outport', ...
                'AutoShapeInputs', false, ...
                'SchedulerBlock', 'Test Sequence', ...
                'SeparateAssessment', true, ...
                'CreateWithoutCompile', false, ...
                'VerificationMode', 'Normal', ...
                'LogOutputs', false, ...
                'RebuildOnOpen', false, ...
                'RebuildModelData', false, ...
                'SaveExternally', false, ...
                'SynchronizationMode', 'SyncOnOpenAndClose');


            created = ...
                sltest.harness.find( ...
                    ownerPath, ...
                    'SearchDepth', 0, ...
                    'Name', harnessName);

            if isempty(created)

                error( ...
                    'Harness not found after creation: %s', ...
                    harnessName);
            end


            save_system( ...
                cfg.TopModel);

            Status(i) = 'OK';
            Message(i) = 'Harness created';

            fprintf('  -> OK\n');
        end


    catch ME

        if st_is_user_interrupt(ME)

            fprintf('\n');
            fprintf('============================================\n');
            fprintf('Harness creation terminated by user.\n');
            fprintf('============================================\n');

            rethrow(ME);
        end

        Status(i) = 'FAIL';
        Message(i) = string(ME.message);

        fprintf('  -> FAIL : %s\n', ...
            ME.message);
    end


    ElapsedSec(i) = ...
        toc(timerValue);

    Timestamp(i) = ...
        string(datetime( ...
            'now', ...
            'Format', 'yyyy-MM-dd HH:mm:ss'));
end


R = table( ...
    T.No, ...
    T.CUTName, ...
    T.CUTPath, ...
    T.HarnessName, ...
    Status, ...
    Message, ...
    ElapsedSec, ...
    Timestamp, ...
    'VariableNames', { ...
        'No', ...
        'CUTName', ...
        'CUTPath', ...
        'HarnessName', ...
        'Status', ...
        'Message', ...
        'ElapsedSec', ...
        'Timestamp'});


st_write_result( ...
    'HarnessCreateResult', ...
    R);


fprintf('\n');
fprintf('============================================\n');
fprintf('Harness Creation Result\n');
fprintf('============================================\n');
fprintf('OK   : %d\n', sum(Status == 'OK'));
fprintf('SKIP : %d\n', sum(Status == 'SKIP'));
fprintf('FAIL : %d\n', sum(Status == 'FAIL'));
fprintf('============================================\n');

end


function tf = st_is_user_interrupt(ME)

id = ...
    lower(char(string(ME.identifier)));

msg = ...
    lower(char(string(ME.message)));

% If Ctrl+C bypasses catch, MATLAB stops naturally. This branch handles
% internal operations that surface the user interrupt as an exception.
tf = ...
    contains(id, 'operationterminated') || ...
    contains(id, 'interrupted') || ...
    contains(msg, 'operation terminated by user') || ...
    contains(msg, 'terminated by user') || ...
    contains(msg, 'interrupted by user');

end
