function R = st_create_harnesses()
%ST_CREATE_HARNESSES Create missing Harnesses from TestManagement.xlsx.
%
% Existing Harnesses are skipped.
% Harness creation uses normal compile mode.
%
% Progress:
%   Each target prints its start time and elapsed time. This is especially
%   useful because sltest.harness.create can take several minutes.

cfg = st_require_runtime_target();

T = st_load_targets( ...
    cfg.OnlyEnabled);

n = height(T);

Status = strings(n,1);
Message = strings(n,1);
ElapsedSec = zeros(n,1);
Timestamp = strings(n,1);


totalTimer = tic;


fprintf('\n');
fprintf('============================================\n');
fprintf('Create Test Harnesses\n');
fprintf('Model : %s\n', cfg.TopModel);
fprintf('Count : %d\n', n);
fprintf('Start : %s\n', st_now_text());
fprintf('============================================\n');


for i = 1:n

    cutName = ...
        char(T.CUTName(i));

    ownerPath = ...
        st_normalize_cut_path( ...
            T.CUTPath(i), ...
            cfg.TopModel);

    harnessName = ...
        char(T.HarnessName(i));

    timerValue = tic;

    st_log(cfg, 'DEBUG', ...
        '[HarnessCreate %d/%d] target resolved | CUT=%s | Harness=%s', ...
        i, n, ownerPath, harnessName);

    fprintf('\n');
    fprintf('--------------------------------------------\n');
    fprintf('[%d/%d] START %s\n', ...
        i, ...
        n, ...
        cutName);
    fprintf('  Time    : %s\n', st_now_text());
    fprintf('  CUT     : %s\n', ownerPath);
    fprintf('  Harness : %s\n', harnessName);
    fprintf('--------------------------------------------\n');


    try

        st_log(cfg, 'TRACE', ...
            '[HarnessCreate %d/%d] getSimulinkBlockHandle start', ...
            i, n);

        blockHandle = ...
            getSimulinkBlockHandle( ...
                ownerPath);

        st_log(cfg, 'TRACE', ...
            '[HarnessCreate %d/%d] getSimulinkBlockHandle done | handle=%g', ...
            i, n, double(blockHandle));

        if blockHandle == -1

            error( ...
                'CUT not found: %s', ...
                ownerPath);
        end

        if ~strcmp( ...
                get_param(blockHandle, 'BlockType'), ...
                'SubSystem')

            error( ...
                'CUT is not a Subsystem: %s', ...
                ownerPath);
        end


        st_log(cfg, 'DEBUG', ...
            '[HarnessCreate %d/%d] checking existing Harness', ...
            i, n);

        existing = ...
            sltest.harness.find( ...
                ownerPath, ...
                'SearchDepth', 0, ...
                'Name', harnessName);

        st_log(cfg, 'DEBUG', ...
            '[HarnessCreate %d/%d] existing Harness count=%d', ...
            i, n, numel(existing));

        if ~isempty(existing)

            Status(i) = 'SKIP';
            Message(i) = 'Harness already exists';

            fprintf('  -> SKIP : already exists\n');

        else

            st_log(cfg, 'DEBUG', ...
                '[HarnessCreate %d/%d] forcing model stopped', ...
                i, n);

            st_force_model_stopped( ...
                cfg.TopModel);

            st_log(cfg, 'DEBUG', ...
                ['[HarnessCreate %d/%d] entering sltest.harness.create. ' ...
                 'This call can take several minutes.'], ...
                i, n);

            fprintf('  -> Creating Harness... start=%s\n', ...
                st_now_text());


            sltest.harness.create( ...
                ownerPath, ...
                'Name', harnessName, ...
                'Source', 'Signal Editor', ...
                'Sink', 'Outport', ...
                'AutoShapeInputs', false, ...
                'SchedulerBlock', 'Test Sequence', ...
                'SeparateAssessment', true, ...
                'CreateWithoutCompile', false, ...
                'VerificationMode', 'Normal', ...
                'LogOutputs', false, ...
                'RebuildOnOpen', false, ...
                'RebuildModelData', false, ...
                'SaveExternally', false, ...
                'SynchronizationMode', 'SyncOnOpenAndClose');


            fprintf('  -> Harness create returned at %s\n', ...
                st_now_text());

            st_log(cfg, 'DEBUG', ...
                '[HarnessCreate %d/%d] sltest.harness.create returned', ...
                i, n);

            st_log(cfg, 'TRACE', ...
                '[HarnessCreate %d/%d] verifying created Harness', ...
                i, n);


            created = ...
                sltest.harness.find( ...
                    ownerPath, ...
                    'SearchDepth', 0, ...
                    'Name', harnessName);

            if isempty(created)

                error( ...
                    'Harness not found after creation: %s', ...
                    harnessName);
            end


            st_log(cfg, 'DEBUG', ...
                '[HarnessCreate %d/%d] save_system start', ...
                i, n);

            save_system( ...
                cfg.TopModel);

            st_log(cfg, 'DEBUG', ...
                '[HarnessCreate %d/%d] save_system done', ...
                i, n);

            Status(i) = 'OK';
            Message(i) = 'Harness created';

            fprintf('  -> OK\n');
        end


    catch ME

        if st_is_user_interrupt(ME)

            fprintf('\n');
            fprintf('============================================\n');
            fprintf('Harness creation terminated by user.\n');
            fprintf('Time    : %s\n', st_now_text());
            fprintf('Elapsed : %s\n', ...
                st_elapsed_text(toc(totalTimer)));
            fprintf('============================================\n');

            rethrow(ME);
        end

        Status(i) = 'FAIL';
        Message(i) = string(ME.message);

        fprintf('  -> FAIL : %s\n', ...
            ME.message);
    end


    ElapsedSec(i) = ...
        toc(timerValue);

    Timestamp(i) = ...
        string(datetime( ...
            'now', ...
            'Format', 'yyyy-MM-dd HH:mm:ss'));


    fprintf('  Finish  : %s\n', st_now_text());
    fprintf('  Elapsed : %s\n', ...
        st_elapsed_text(ElapsedSec(i)));
    fprintf('  Total   : %s\n', ...
        st_elapsed_text(toc(totalTimer)));

    st_log(cfg, 'DEBUG', ...
        '[HarnessCreate %d/%d] finished | status=%s | elapsed=%.3f sec', ...
        i, n, char(Status(i)), ElapsedSec(i));
end


R = table( ...
    T.No, ...
    T.CUTName, ...
    T.CUTPath, ...
    T.HarnessName, ...
    Status, ...
    Message, ...
    ElapsedSec, ...
    Timestamp, ...
    'VariableNames', { ...
        'No', ...
        'CUTName', ...
        'CUTPath', ...
        'HarnessName', ...
        'Status', ...
        'Message', ...
        'ElapsedSec', ...
        'Timestamp'});


st_write_result( ...
    'HarnessCreateResult', ...
    R);


fprintf('\n');
fprintf('============================================\n');
fprintf('Harness Creation Result\n');
fprintf('============================================\n');
fprintf('OK      : %d\n', sum(Status == 'OK'));
fprintf('SKIP    : %d\n', sum(Status == 'SKIP'));
fprintf('FAIL    : %d\n', sum(Status == 'FAIL'));
fprintf('End     : %s\n', st_now_text());
fprintf('Elapsed : %s\n', st_elapsed_text(toc(totalTimer)));
fprintf('============================================\n');

end


function text = st_now_text()

text = ...
    char( ...
        datetime( ...
            'now', ...
            'Format', ...
            'yyyy-MM-dd HH:mm:ss'));

end


function text = st_elapsed_text(secondsValue)

secondsValue = ...
    max( ...
        0, ...
        double(secondsValue));

hoursValue = ...
    floor(secondsValue / 3600);

minutesValue = ...
    floor(mod(secondsValue, 3600) / 60);

secondsPart = ...
    mod(secondsValue, 60);

text = ...
    sprintf( ...
        '%02d:%02d:%06.3f', ...
        hoursValue, ...
        minutesValue, ...
        secondsPart);

end


function tf = st_is_user_interrupt(ME)

id = ...
    lower(char(string(ME.identifier)));

msg = ...
    lower(char(string(ME.message)));

% If Ctrl+C bypasses catch, MATLAB stops naturally. This branch handles
% internal operations that surface the user interrupt as an exception.
tf = ...
    contains(id, 'operationterminated') || ...
    contains(id, 'interrupted') || ...
    contains(msg, 'operation terminated by user') || ...
    contains(msg, 'terminated by user') || ...
    contains(msg, 'interrupted by user');

end
