function names = st_collect_signal_editor_scenario_names(harnessName, topModel)
%ST_COLLECT_SIGNAL_EDITOR_SCENARIO_NAMES
% Return Signal Editor ActiveScenario element names in Dataset order.
%
% This is used only to determine how many Assessment Input ports belong to
% the input scenario before Harness output symbols begin.
%
% No signal-name normalization is performed.

harnessName = char(harnessName);
topModel = char(topModel);

sigBlock = ...
    st_find_signal_editor_block( ...
        harnessName);

scenarioName = ...
    char( ...
        get_param( ...
            sigBlock, ...
            'ActiveScenario'));

if isempty(scenarioName)
    error( ...
        'Signal Editor ActiveScenario is empty: %s', ...
        sigBlock);
end

fileName = ...
    get_param( ...
        sigBlock, ...
        'Filename');

matPath = ...
    st_resolve_data_file( ...
        fileName, ...
        topModel);

if ~isfile(matPath)
    error( ...
        'Signal Editor data file not found: %s', ...
        matPath);
end

S = ...
    load( ...
        matPath, ...
        scenarioName);

if ~isfield(S, scenarioName)
    error( ...
        'Active scenario variable not found in MAT file: %s', ...
        scenarioName);
end

scenario = ...
    S.(scenarioName);

names = ...
    scenario_element_names( ...
        scenario);

end


function names = scenario_element_names(scenario)
names = strings(0,1);

% Primary path for Simulink.SimulationData.Dataset.
try
    rawNames = ...
        getElementNames( ...
            scenario);

    if ischar(rawNames)
        names = string({rawNames});
    else
        names = string(rawNames(:));
    end

    return;
catch
end

% Fallback for Dataset-compatible objects.
try
    n = scenario.numElements;
    names = strings(n,1);

    for i = 1:n
        element = ...
            getElement( ...
                scenario, ...
                i);

        try
            names(i) = string(element.Name);
        catch
            names(i) = ...
                sprintf( ...
                    '<ScenarioElement%d>', ...
                    i);
        end
    end

    return;
catch
end

error( ...
    ['Could not read Signal Editor scenario element names. ' ...
     'Scenario class: %s'], ...
    class(scenario));
end
