function R = st_diagnose_assessment_port_mapping(ownerPath, harnessName)
%ST_DIAGNOSE_ASSESSMENT_PORT_MAPPING Verify Harness Outport <-> Assessment Input mapping.
%
% This diagnostic does not use Targets.No or the management Excel.
% The CUT owner path and Harness name are supplied directly.
%
% Usage:
%   R = st_diagnose_assessment_port_mapping( ...
%       'TEST_TARGET_MODEL_NAME/SubsystemA', ...
%       'SubsystemA_Harness1');
%
% What this checks:
%   1. Stateflow.Data.Port is read for each Test Assessment Input symbol.
%      This gives the actual Assessment input port number for the symbol.
%
%   2. For each Assessment input port, the connected Simulink line source
%      port is collected.
%
%   3. For each top-level Harness Outport, the source port feeding that
%      Outport is collected.
%
%   4. Harness Outport N and Assessment Input N are compared physically.
%      If both are fed by the same Simulink source port handle,
%      SameSourcePort is true.
%
% Notes:
%   - No signal-name normalization is performed.
%   - '/', spaces, '-', and other characters are preserved exactly as read.
%   - Assessment symbol names are reported exactly as Stateflow created them.

if nargin < 2 || ...
        isempty(ownerPath) || ...
        isempty(harnessName)

    error([ ...
        'Usage: st_diagnose_assessment_port_mapping(' ...
        '''TEST_TARGET_MODEL_NAME/CUTPath'', ''HarnessName'')']);
end

cfg = st_require_runtime_target();

ownerPath = ...
    st_normalize_cut_path( ...
        ownerPath, ...
        cfg.TopModel);

harnessName = ...
    char(harnessName);

fprintf('\n');
fprintf('============================================\n');
fprintf('Assessment Port Mapping Diagnostic\n');
fprintf('============================================\n');
fprintf('Path    : %s\n', ownerPath);
fprintf('Harness : %s\n', harnessName);
fprintf('============================================\n');

st_force_model_stopped(cfg.TopModel);
sltest.harness.load(ownerPath, harnessName);

cleanupObj = ...
    onCleanup( ...
        @() st_diag_close_harness_quiet( ...
            ownerPath, ...
            harnessName)); %#ok<NASGU>

assess = ...
    st_find_assessment_block( ...
        harnessName);

fprintf('Assessment: %s\n', assess);

assessmentSymbols = ...
    st_diag_collect_assessment_symbols_by_port( ...
        assess);

assessmentConnections = ...
    st_diag_collect_assessment_connections( ...
        assess);

harnessOutputs = ...
    st_diag_collect_harness_outputs( ...
        harnessName);

R = ...
    st_diag_build_mapping_table( ...
        assessmentSymbols, ...
        assessmentConnections, ...
        harnessOutputs);

fprintf('\n');
fprintf('--- Port Mapping ---\n');
disp(R);

fprintf('\n');
fprintf('--- Assessment Symbols by actual Stateflow Port ---\n');
disp(assessmentSymbols);

fprintf('\n');
fprintf('--- Harness Outports ---\n');
disp(harnessOutputs);

sameCount = ...
    sum(R.SameSourcePort);

comparableCount = ...
    sum(R.SourceComparable);

fprintf('\n');
fprintf('============================================\n');
fprintf('Diagnostic Summary\n');
fprintf('============================================\n');
fprintf('Assessment inputs : %d\n', height(assessmentSymbols));
fprintf('Harness outports  : %d\n', height(harnessOutputs));
fprintf('Comparable ports  : %d\n', comparableCount);
fprintf('Same source ports : %d\n', sameCount);

if comparableCount > 0 && ...
        sameCount == comparableCount && ...
        height(assessmentSymbols) == height(harnessOutputs)

    fprintf('RESULT: PASS - same-number ports share the same source port.\n');

elseif comparableCount == 0

    fprintf(['RESULT: INCONCLUSIVE - source port handles could not be ' ...
        'compared. Check the printed paths and line names.\n']);

else

    fprintf(['RESULT: CHECK - at least one same-number port does not ' ...
        'share the same immediate source port.\n']);
end

fprintf('============================================\n');

end


function S = st_diag_collect_assessment_symbols_by_port(assessmentBlock)

allData = ...
    find( ...
        sfroot, ...
        '-isa', ...
        'Stateflow.Data');

Port = [];
SymbolName = strings(0,1);
DataPath = strings(0,1);

for i = 1:numel(allData)

    dataObj = ...
        allData(i);

    try

        if ~strcmp( ...
                char(dataObj.Scope), ...
                'Input')

            continue;
        end

        if ~strcmp( ...
                char(dataObj.Path), ...
                assessmentBlock)

            continue;
        end

        portValue = ...
            double(dataObj.Port);

        if isempty(portValue) || ...
                ~isscalar(portValue) || ...
                ~isfinite(portValue)

            continue;
        end

        Port(end+1,1) = portValue; %#ok<AGROW>
        SymbolName(end+1,1) = string(dataObj.Name); %#ok<AGROW>
        DataPath(end+1,1) = string(dataObj.Path); %#ok<AGROW>

    catch
    end
end

if isempty(Port)

    error( ...
        ['Could not find Stateflow input data objects for Assessment: %s. ' ...
         'The Stateflow API did not expose chart-level Input data.'], ...
        assessmentBlock);
end

[Port, order] = ...
    sort(Port);

SymbolName = SymbolName(order);
DataPath = DataPath(order);

if numel(unique(Port)) ~= numel(Port)
    error('Duplicate Assessment Stateflow input Port values were found.');
end

S = ...
    table( ...
        Port, ...
        SymbolName, ...
        DataPath, ...
        'VariableNames', { ...
            'AssessmentPort', ...
            'AssessmentSymbol', ...
            'AssessmentDataPath'});

end


function C = st_diag_collect_assessment_connections(assessmentBlock)

portHandles = ...
    get_param( ...
        assessmentBlock, ...
        'PortHandles');

inports = ...
    portHandles.Inport(:);

n = numel(inports);

AssessmentPort = (1:n).';
LineName = strings(n,1);
SourceBlock = strings(n,1);
SourcePort = nan(n,1);
SourcePortHandle = nan(n,1);
Connected = false(n,1);

for i = 1:n

    portHandle = ...
        inports(i);

    lineHandle = ...
        get_param( ...
            portHandle, ...
            'Line');

    if lineHandle == -1
        continue;
    end

    Connected(i) = true;

    lineName = ...
        get_param( ...
            lineHandle, ...
            'Name');

    LineName(i) = ...
        string(lineName);

    srcPortHandle = ...
        get_param( ...
            lineHandle, ...
            'SrcPortHandle');

    if isempty(srcPortHandle) || ...
            srcPortHandle == -1

        continue;
    end

    SourcePortHandle(i) = ...
        double(srcPortHandle);

    try

        SourcePort(i) = ...
            double( ...
                get_param( ...
                    srcPortHandle, ...
                    'PortNumber'));

    catch
    end

    try

        sourceBlockHandle = ...
            get_param( ...
                srcPortHandle, ...
                'Parent');

        SourceBlock(i) = ...
            string( ...
                getfullname( ...
                    sourceBlockHandle));

    catch
    end
end

C = ...
    table( ...
        AssessmentPort, ...
        LineName, ...
        SourceBlock, ...
        SourcePort, ...
        SourcePortHandle, ...
        Connected, ...
        'VariableNames', { ...
            'AssessmentPort', ...
            'AssessmentLineName', ...
            'AssessmentSourceBlock', ...
            'AssessmentSourcePort', ...
            'AssessmentSourcePortHandle', ...
            'AssessmentConnected'});

end


function H = st_diag_collect_harness_outputs(harnessName)

outportBlocks = ...
    find_system( ...
        harnessName, ...
        'SearchDepth', 1, ...
        'Type', 'Block', ...
        'BlockType', 'Outport');

n = numel(outportBlocks);

HarnessOutport = zeros(n,1);
HarnessSignalName = strings(n,1);
HarnessOutportBlock = strings(n,1);
HarnessSourceBlock = strings(n,1);
HarnessSourcePort = nan(n,1);
HarnessSourcePortHandle = nan(n,1);
HarnessConnected = false(n,1);

for i = 1:n

    blockPath = ...
        outportBlocks{i};

    HarnessOutport(i) = ...
        str2double( ...
            get_param( ...
                blockPath, ...
                'Port'));

    HarnessOutportBlock(i) = ...
        string( ...
            get_param( ...
                blockPath, ...
                'Name'));

    portHandles = ...
        get_param( ...
            blockPath, ...
            'PortHandles');

    if isempty(portHandles.Inport) || ...
            portHandles.Inport == -1

        continue;
    end

    lineHandle = ...
        get_param( ...
            portHandles.Inport, ...
            'Line');

    if lineHandle == -1
        continue;
    end

    HarnessConnected(i) = true;

    lineName = ...
        get_param( ...
            lineHandle, ...
            'Name');

    if isempty(lineName)

        lineName = ...
            get_param( ...
                blockPath, ...
                'Name');
    end

    HarnessSignalName(i) = ...
        string(lineName);

    srcPortHandle = ...
        get_param( ...
            lineHandle, ...
            'SrcPortHandle');

    if isempty(srcPortHandle) || ...
            srcPortHandle == -1

        continue;
    end

    HarnessSourcePortHandle(i) = ...
        double(srcPortHandle);

    try

        HarnessSourcePort(i) = ...
            double( ...
                get_param( ...
                    srcPortHandle, ...
                    'PortNumber'));

    catch
    end

    try

        sourceBlockHandle = ...
            get_param( ...
                srcPortHandle, ...
                'Parent');

        HarnessSourceBlock(i) = ...
            string( ...
                getfullname( ...
                    sourceBlockHandle));

    catch
    end
end

[HarnessOutport, order] = ...
    sort(HarnessOutport);

HarnessSignalName = HarnessSignalName(order);
HarnessOutportBlock = HarnessOutportBlock(order);
HarnessSourceBlock = HarnessSourceBlock(order);
HarnessSourcePort = HarnessSourcePort(order);
HarnessSourcePortHandle = HarnessSourcePortHandle(order);
HarnessConnected = HarnessConnected(order);

H = ...
    table( ...
        HarnessOutport, ...
        HarnessSignalName, ...
        HarnessOutportBlock, ...
        HarnessSourceBlock, ...
        HarnessSourcePort, ...
        HarnessSourcePortHandle, ...
        HarnessConnected);

end


function R = st_diag_build_mapping_table(S, C, H)

ports = ...
    unique( ...
        [ ...
            S.AssessmentPort; ...
            C.AssessmentPort; ...
            H.HarnessOutport], ...
        'sorted');

n = numel(ports);

AssessmentPort = ports;
AssessmentSymbol = strings(n,1);
AssessmentLineName = strings(n,1);
AssessmentSourceBlock = strings(n,1);
AssessmentSourcePort = nan(n,1);
HarnessSignalName = strings(n,1);
HarnessOutportBlock = strings(n,1);
HarnessSourceBlock = strings(n,1);
HarnessSourcePort = nan(n,1);
SourceComparable = false(n,1);
SameSourcePort = false(n,1);

for i = 1:n

    p = ...
        ports(i);

    sRow = ...
        find( ...
            S.AssessmentPort == p, ...
            1, ...
            'first');

    cRow = ...
        find( ...
            C.AssessmentPort == p, ...
            1, ...
            'first');

    hRow = ...
        find( ...
            H.HarnessOutport == p, ...
            1, ...
            'first');

    if ~isempty(sRow)
        AssessmentSymbol(i) = S.AssessmentSymbol(sRow);
    end

    if ~isempty(cRow)

        AssessmentLineName(i) = C.AssessmentLineName(cRow);
        AssessmentSourceBlock(i) = C.AssessmentSourceBlock(cRow);
        AssessmentSourcePort(i) = C.AssessmentSourcePort(cRow);
    end

    if ~isempty(hRow)

        HarnessSignalName(i) = H.HarnessSignalName(hRow);
        HarnessOutportBlock(i) = H.HarnessOutportBlock(hRow);
        HarnessSourceBlock(i) = H.HarnessSourceBlock(hRow);
        HarnessSourcePort(i) = H.HarnessSourcePort(hRow);
    end

    if ~isempty(cRow) && ...
            ~isempty(hRow) && ...
            isfinite(C.AssessmentSourcePortHandle(cRow)) && ...
            isfinite(H.HarnessSourcePortHandle(hRow))

        SourceComparable(i) = true;

        SameSourcePort(i) = ...
            C.AssessmentSourcePortHandle(cRow) == ...
            H.HarnessSourcePortHandle(hRow);
    end
end

R = ...
    table( ...
        AssessmentPort, ...
        AssessmentSymbol, ...
        AssessmentLineName, ...
        AssessmentSourceBlock, ...
        AssessmentSourcePort, ...
        HarnessSignalName, ...
        HarnessOutportBlock, ...
        HarnessSourceBlock, ...
        HarnessSourcePort, ...
        SourceComparable, ...
        SameSourcePort);

end


function st_diag_close_harness_quiet(ownerPath, harnessName)

try

    sltest.harness.close( ...
        ownerPath, ...
        harnessName);

catch
end

end
