function R = st_enable_harness_output_logging(harnessName)
%ST_ENABLE_HARNESS_OUTPUT_LOGGING
% Harness 최상위 Outport에 연결된 신호를 signal logging 대상으로 설정합니다.
%
% Expected value 자동 갱신 시 Test Result에서 실제 값을 얻기 위해 사용합니다.
%
% 처리 방식:
%   Harness root Outport
%       <- input line
%       <- source output port
%
% source output port에:
%   DataLogging         = on
%   DataLoggingNameMode = Custom
%   DataLoggingName     = Harness Outport signal name
%
% 내부 Subsystem의 Outport는 대상이 아닙니다.

harnessName = char(harnessName);

if ~bdIsLoaded(harnessName)

    error( ...
        'Harness가 load되어 있지 않습니다: %s', ...
        harnessName);
end


%% Harness 전체 signal logging enable

set_param( ...
    harnessName, ...
    'SignalLogging', ...
    'on');


%% Harness 최상위 Outport

outportBlocks = ...
    find_system( ...
        harnessName, ...
        'SearchDepth', ...
        1, ...
        'Type', ...
        'Block', ...
        'BlockType', ...
        'Outport');

n = numel(outportBlocks);

OutportBlock = strings(n,1);
SignalName = strings(n,1);
Status = strings(n,1);
Message = strings(n,1);


for i = 1:n

    outBlock = ...
        outportBlocks{i};

    OutportBlock(i) = ...
        string( ...
            get_param( ...
                outBlock, ...
                'Name'));

    try

        portHandles = ...
            get_param( ...
                outBlock, ...
                'PortHandles');

        if isempty(portHandles.Inport) || ...
                portHandles.Inport == -1

            error( ...
                'Outport input port handle을 찾지 못했습니다.');
        end


        lineHandle = ...
            get_param( ...
                portHandles.Inport, ...
                'Line');

        if lineHandle == -1

            error( ...
                'Outport에 연결된 신호가 없습니다.');
        end


        signalName = ...
            get_param( ...
                lineHandle, ...
                'Name');

        if isempty(signalName)

            signalName = ...
                get_param( ...
                    outBlock, ...
                    'Name');
        end

        SignalName(i) = ...
            string(signalName);


        srcPortHandle = ...
            get_param( ...
                lineHandle, ...
                'SrcPortHandle');

        if isempty(srcPortHandle) || ...
                srcPortHandle == -1

            error( ...
                'Signal source port handle을 찾지 못했습니다.');
        end


        set_param( ...
            srcPortHandle, ...
            'DataLogging', ...
            'on', ...
            'DataLoggingNameMode', ...
            'Custom', ...
            'DataLoggingName', ...
            signalName);


        Status(i) = ...
            'OK';

        Message(i) = ...
            'Signal logging enabled';


    catch ME

        Status(i) = ...
            'FAIL';

        Message(i) = ...
            string(ME.message);
    end
end


R = table( ...
    OutportBlock, ...
    SignalName, ...
    Status, ...
    Message);

end
