function st_log(cfg, level, formatText, varargin)
%ST_LOG Optional timestamped diagnostic log.
%
% cfg.VerboseLogging == true
%   INFO / DEBUG / TRACE messages are printed.
%
% cfg.VerboseLogging == false
%   INFO / DEBUG / TRACE messages are suppressed.
%
% WARN / ERROR are always printed.

if nargin < 3
    error('Usage: st_log(cfg, level, formatText, ...)');
end

level = ...
    upper( ...
        strtrim( ...
            char(level)));

alwaysPrint = ...
    any( ...
        strcmp( ...
            level, ...
            {'WARN', 'ERROR'}));

verboseEnabled = false;

if isstruct(cfg) && ...
        isfield(cfg, 'VerboseLogging')

    verboseEnabled = ...
        logical(cfg.VerboseLogging);
end

if ~alwaysPrint && ...
        ~verboseEnabled

    return;
end

message = ...
    sprintf( ...
        char(formatText), ...
        varargin{:});

timestamp = ...
    char( ...
        datetime( ...
            'now', ...
            'Format', ...
            'yyyy-MM-dd HH:mm:ss'));

fprintf( ...
    '[%s][%s] %s\n', ...
    timestamp, ...
    level, ...
    message);

end
