function st_prepare_assessment_scenario( ...
        assessmentBlock, ...
        scenarioNames, ...
        verifyAction, ...
        transitionCondition)
%ST_PREPARE_ASSESSMENT_SCENARIO Rebuild scenarios with identical steps.
%
%   scenarioName
%      step1 --transitionCondition--> step2
%
%      step1 Action: empty
%      step2 Action: verifyAction
%
% Default transitionCondition:
%   true

if nargin < 4 || isempty(transitionCondition)
    transitionCondition = 'true';
end

assessmentBlock = char(assessmentBlock);
scenarioNames = normalize_cellstr(scenarioNames);
verifyAction = char(verifyAction);
transitionCondition = char(transitionCondition);

if isempty(scenarioNames)
    error('At least one Assessment scenario name is required.');
end

ensure_scenario_set(assessmentBlock, scenarioNames);

for scenarioIndex = 1:numel(scenarioNames)
    prepare_one_scenario(assessmentBlock, scenarioNames{scenarioIndex}, ...
        verifyAction, transitionCondition);
end

sltest.testsequence.activateScenario( ...
    assessmentBlock, scenarioNames{1});

end


function ensure_scenario_set(assessmentBlock, scenarioNames)

if ~sltest.testsequence.isUsingScenarios(assessmentBlock)

    sltest.testsequence.useScenario( ...
        assessmentBlock, ...
        scenarioNames{1});

else

    scenarios = ...
        sltest.testsequence.getAllScenarios( ...
            assessmentBlock);

    scenarios = ...
        normalize_cellstr( ...
            scenarios);

    if isempty(scenarios)

        error( ...
            'Scenario mode is enabled but no scenario exists: %s', ...
            assessmentBlock);
    end

    keepScenario = scenarios{1};

    for k = numel(scenarios):-1:2

        sltest.testsequence.deleteScenario( ...
            assessmentBlock, ...
            scenarios{k});
    end

    if ~strcmp( ...
            keepScenario, ...
            scenarioNames{1})

        sltest.testsequence.editScenario( ...
            assessmentBlock, ...
            keepScenario, ...
            'Name', ...
            scenarioNames{1});
    end
end

for k = 2:numel(scenarioNames)
    sltest.testsequence.addScenario(assessmentBlock, scenarioNames{k});
end
end


function prepare_one_scenario( ...
        assessmentBlock, scenarioName, verifyAction, transitionCondition)

sltest.testsequence.activateScenario(assessmentBlock, scenarioName);


%% ============================================================
% Scenario Step 정리
%% ============================================================

prefix = [scenarioName '.'];

steps = ...
    normalize_cellstr( ...
        sltest.testsequence.findStep( ...
            assessmentBlock));

scenarioSteps = ...
    steps( ...
        strncmp_many( ...
            steps, ...
            prefix));


topSteps = {};

for i = 1:numel(scenarioSteps)

    rest = ...
        scenarioSteps{i}( ...
            length(prefix)+1:end);

    if isempty(strfind(rest, '.')) %#ok<STREMP>

        topSteps{end+1,1} = ...
            scenarioSteps{i}; %#ok<AGROW>
    end
end


%% ============================================================
% Step 1
%% ============================================================

if isempty(topSteps)

    step1Path = ...
        [prefix 'step1'];

    sltest.testsequence.addStep( ...
        assessmentBlock, ...
        step1Path, ...
        'Action', ...
        '', ...
        'IsWhenStep', ...
        false);

else

    keepStep = ...
        topSteps{1};


    %% 다른 top-level step 제거

    for k = numel(topSteps):-1:2

        sltest.testsequence.deleteStep( ...
            assessmentBlock, ...
            topSteps{k});
    end


    %% retained step 아래 child 제거

    steps = ...
        normalize_cellstr( ...
            sltest.testsequence.findStep( ...
                assessmentBlock));

    childPrefix = ...
        [keepStep '.'];

    children = ...
        steps( ...
            strncmp_many( ...
                steps, ...
                childPrefix));

    [~, order] = ...
        sort( ...
            cellfun( ...
                @length, ...
                children), ...
            'descend');

    children = ...
        children(order);

    for k = 1:numel(children)

        try

            sltest.testsequence.deleteStep( ...
                assessmentBlock, ...
                children{k});

        catch
        end
    end


    %% 기존 transition 제거

    transitionCount = ...
        sltest.testsequence.readStep( ...
            assessmentBlock, ...
            keepStep, ...
            'TransitionCount');

    for k = double(transitionCount):-1:1

        sltest.testsequence.deleteTransition( ...
            assessmentBlock, ...
            keepStep, ...
            k);
    end


    %% step1으로 정규화

    sltest.testsequence.editStep( ...
        assessmentBlock, ...
        keepStep, ...
        'Name', ...
        'step1', ...
        'Action', ...
        '', ...
        'IsWhenStep', ...
        false);

    step1Path = ...
        [prefix 'step1'];
end


%% ============================================================
% Step 2
%% ============================================================

step2Path = ...
    [prefix 'step2'];

sltest.testsequence.addStepAfter( ...
    assessmentBlock, ...
    step2Path, ...
    step1Path, ...
    'Action', ...
    verifyAction, ...
    'IsWhenStep', ...
    false);


%% ============================================================
% Transition
%% ============================================================

sltest.testsequence.addTransition( ...
    assessmentBlock, ...
    step1Path, ...
    transitionCondition, ...
    step2Path);

end


function c = normalize_cellstr(v)

if isempty(v)

    c = {};

elseif iscell(v)

    c = cellfun( ...
        @char, ...
        v(:), ...
        'UniformOutput', ...
        false);

elseif isstring(v)

    c = cellstr(v(:));

elseif ischar(v)

    c = {v};

else

    c = cellstr(string(v(:)));
end

end


function mask = strncmp_many(c, prefix)

mask = false(size(c));

for i = 1:numel(c)

    mask(i) = ...
        length(c{i}) >= length(prefix) && ...
        strncmp( ...
            c{i}, ...
            prefix, ...
            length(prefix));
end

end
