function [R, Summary] = st_show_assessment_scenario_output_order(startIndex, endIndex)
%ST_SHOW_ASSESSMENT_SCENARIO_OUTPUT_ORDER
% Preview the hypothesis:
%
%   Assessment Input order
%       = Signal Editor active-scenario variables first
%       + Harness output signals second
%
% No automatic correctness judgment is made from signal names.
% The table is intended for manual visual confirmation.
%
% startIndex/endIndex:
%   positional rows in st_load_targets(false)
%   Targets.No is shown only as reference and is NOT used for selection.
%
% Example:
%   [R, Summary] = ...
%       st_show_assessment_scenario_output_order(1, 20);
%
% Main preview columns:
%   Order
%   SourceType          - SCENARIO or OUTPUT
%   CompareSignalName   - scenario element name or harness output signal name
%   AssessmentPort
%   AssessmentSymbol
%
% PairState:
%   PAIR              - both comparison item and Assessment symbol exist
%   NO_ASSESSMENT     - comparison item exists, Assessment symbol does not
%   NO_COMPARE_TARGET - Assessment symbol exists, comparison item does not

if nargin < 2
    error( ...
        ['Usage: st_show_assessment_scenario_output_order(' ...
         'startIndex, endIndex)']);
end

if ~isscalar(startIndex) || ...
        ~isscalar(endIndex) || ...
        ~isfinite(startIndex) || ...
        ~isfinite(endIndex) || ...
        startIndex < 1 || ...
        endIndex < startIndex || ...
        mod(startIndex,1) ~= 0 || ...
        mod(endIndex,1) ~= 0

    error( ...
        'startIndex/endIndex must be positive integer row positions.');
end

cfg = ...
    st_require_runtime_target();

T = ...
    st_load_targets(false);

if endIndex > height(T)
    error( ...
        'endIndex=%d exceeds Targets row count=%d.', ...
        endIndex, ...
        height(T));
end

selected = ...
    startIndex:endIndex;

detailParts = ...
    cell(numel(selected),1);

TargetIndex = zeros(numel(selected),1);
No = zeros(numel(selected),1);
CUTName = strings(numel(selected),1);
CUTPath = strings(numel(selected),1);
HarnessName = strings(numel(selected),1);
ScenarioCount = zeros(numel(selected),1);
OutputCount = zeros(numel(selected),1);
CompareCount = zeros(numel(selected),1);
AssessmentCount = zeros(numel(selected),1);
CountMatch = false(numel(selected),1);
Status = strings(numel(selected),1);
Message = strings(numel(selected),1);

fprintf('\n');
fprintf('============================================\n');
fprintf('Assessment Scenario + Output Order Preview\n');
fprintf('Rows  : %d ~ %d\n', ...
    startIndex, ...
    endIndex);
fprintf('Rule  : SCENARIO first, then OUTPUT\n');
fprintf('============================================\n');

for k = 1:numel(selected)

    i = ...
        selected(k);

    TargetIndex(k) = i;
    No(k) = T.No(i);
    CUTName(k) = T.CUTName(i);
    CUTPath(k) = T.CUTPath(i);
    HarnessName(k) = T.HarnessName(i);

    ownerPath = ...
        st_normalize_cut_path( ...
            T.CUTPath(i), ...
            cfg.TopModel);

    harnessName = ...
        char(T.HarnessName(i));

    fprintf('\n');
    fprintf('--------------------------------------------\n');
    fprintf('[%d/%d] TargetIndex=%d | No=%g\n', ...
        k, ...
        numel(selected), ...
        i, ...
        T.No(i));
    fprintf('CUT     : %s\n', ...
        char(T.CUTName(i)));
    fprintf('Harness : %s\n', ...
        harnessName);
    fprintf('--------------------------------------------\n');

    try

        st_force_model_stopped( ...
            cfg.TopModel);

        sltest.harness.load( ...
            ownerPath, ...
            harnessName);

        cleanupObj = ...
            onCleanup( ...
                @() st_close_harness_quiet( ...
                    ownerPath, ...
                    harnessName)); %#ok<NASGU>

        assess = ...
            st_find_assessment_block( ...
                harnessName);

        A = ...
            collect_assessment_inputs_by_port( ...
                assess);

        [scenarioNames, scenarioName, dataFile] = ...
            collect_signal_editor_scenario_names( ...
                harnessName, ...
                cfg.TopModel);

        O = ...
            st_collect_harness_output_signals( ...
                harnessName);

        % Only connected/usable Harness output signals become comparison
        % targets. Keep the same behavior as the verification-side output
        % collector: an empty SignalName is not a valid signal target.
        O = ...
            O(strlength(O.SignalName) > 0, :);

        ScenarioCount(k) = ...
            numel(scenarioNames);

        OutputCount(k) = ...
            height(O);

        CompareCount(k) = ...
            ScenarioCount(k) + OutputCount(k);

        AssessmentCount(k) = ...
            height(A);

        CountMatch(k) = ...
            CompareCount(k) == AssessmentCount(k);

        CompareSourceType = ...
            [ ...
                repmat("SCENARIO", ScenarioCount(k), 1); ...
                repmat("OUTPUT", OutputCount(k), 1)];

        CompareSignalName = ...
            [ ...
                scenarioNames(:); ...
                O.SignalName(:)];

        CompareSourcePort = ...
            [ ...
                (1:ScenarioCount(k)).'; ...
                O.Port(:)];

        compareN = ...
            numel(CompareSignalName);

        assessmentN = ...
            height(A);

        rowCount = ...
            max(compareN, assessmentN);

        Order = ...
            (1:rowCount).';

        SourceType = ...
            strings(rowCount,1);

        CompareName = ...
            strings(rowCount,1);

        SourcePort = ...
            nan(rowCount,1);

        AssessmentPort = ...
            nan(rowCount,1);

        AssessmentSymbol = ...
            strings(rowCount,1);

        PairState = ...
            strings(rowCount,1);

        if compareN > 0

            SourceType(1:compareN) = ...
                CompareSourceType;

            CompareName(1:compareN) = ...
                CompareSignalName;

            SourcePort(1:compareN) = ...
                CompareSourcePort;
        end

        if assessmentN > 0

            AssessmentPort(1:assessmentN) = ...
                A.AssessmentPort;

            AssessmentSymbol(1:assessmentN) = ...
                A.AssessmentSymbol;
        end

        for r = 1:rowCount

            hasCompare = ...
                r <= compareN;

            hasAssessment = ...
                r <= assessmentN;

            if hasCompare && hasAssessment

                PairState(r) = ...
                    'PAIR';

            elseif hasCompare

                PairState(r) = ...
                    'NO_ASSESSMENT';

            else

                PairState(r) = ...
                    'NO_COMPARE_TARGET';
            end
        end

        D = ...
            table( ...
                repmat(i, rowCount, 1), ...
                repmat(T.No(i), rowCount, 1), ...
                repmat(T.CUTName(i), rowCount, 1), ...
                repmat(T.CUTPath(i), rowCount, 1), ...
                repmat(T.HarnessName(i), rowCount, 1), ...
                repmat(string(scenarioName), rowCount, 1), ...
                repmat(string(dataFile), rowCount, 1), ...
                Order, ...
                SourceType, ...
                CompareName, ...
                SourcePort, ...
                AssessmentPort, ...
                AssessmentSymbol, ...
                PairState, ...
                'VariableNames', { ...
                    'TargetIndex', ...
                    'No', ...
                    'CUTName', ...
                    'CUTPath', ...
                    'HarnessName', ...
                    'ActiveScenario', ...
                    'SignalEditorDataFile', ...
                    'Order', ...
                    'SourceType', ...
                    'CompareSignalName', ...
                    'SourcePort', ...
                    'AssessmentPort', ...
                    'AssessmentSymbol', ...
                    'PairState'});

        detailParts{k} = ...
            D;

        if CountMatch(k)

            Status(k) = ...
                'OK';

            Message(k) = ...
                'Counts match; review row order manually';

        else

            Status(k) = ...
                'CHECK';

            Message(k) = ...
                sprintf( ...
                    ['Count mismatch: Scenario=%d, Output=%d, ' ...
                     'CompareTotal=%d, Assessment=%d'], ...
                    ScenarioCount(k), ...
                    OutputCount(k), ...
                    CompareCount(k), ...
                    AssessmentCount(k));
        end

        fprintf('Scenario : %s\n', ...
            scenarioName);
        fprintf('Scenario variables : %d\n', ...
            ScenarioCount(k));
        fprintf('Output signals      : %d\n', ...
            OutputCount(k));
        fprintf('Assessment symbols  : %d\n', ...
            AssessmentCount(k));

        fprintf('\n');
        fprintf('--- Proposed Matching Order ---\n');

        disp(D(:, { ...
            'Order', ...
            'SourceType', ...
            'CompareSignalName', ...
            'AssessmentPort', ...
            'AssessmentSymbol'}));

        clear cleanupObj

        st_close_harness_quiet( ...
            ownerPath, ...
            harnessName);

    catch ME

        detailParts{k} = ...
            table();

        Status(k) = ...
            'FAIL';

        Message(k) = ...
            string(ME.message);

        fprintf('FAIL: %s\n', ...
            ME.message);
    end
end

nonEmpty = ...
    ~cellfun( ...
        @(x) isempty(x) || height(x) == 0, ...
        detailParts);

if any(nonEmpty)

    R = ...
        vertcat( ...
            detailParts{nonEmpty});

else

    R = ...
        table();
end

Summary = ...
    table( ...
        TargetIndex, ...
        No, ...
        CUTName, ...
        CUTPath, ...
        HarnessName, ...
        ScenarioCount, ...
        OutputCount, ...
        CompareCount, ...
        AssessmentCount, ...
        CountMatch, ...
        Status, ...
        Message);

fprintf('\n');
fprintf('============================================\n');
fprintf('Scenario + Output Order Summary\n');
fprintf('============================================\n');
disp(Summary);

try

    st_write_result( ...
        'AssessmentScenarioOutputOrderSummary', ...
        Summary);

    if ~isempty(R)

        st_write_result( ...
            'AssessmentScenarioOutputOrderDetail', ...
            R);
    end

catch ME

    warning( ...
        'Preview result write failed: %s', ...
        ME.message);
end

st_force_model_stopped( ...
    cfg.TopModel);

end


%% ============================================================
% Assessment Input Symbols by Stateflow.Data.Port
%% ============================================================

function A = ...
    collect_assessment_inputs_by_port( ...
        assessmentBlock)

dataObjects = ...
    find( ...
        sfroot, ...
        '-isa', ...
        'Stateflow.Data');

Port = [];
Symbol = strings(0,1);

for i = 1:numel(dataObjects)

    obj = ...
        dataObjects(i);

    try

        if ~strcmp( ...
                char(obj.Scope), ...
                'Input')

            continue;
        end

        if ~strcmp( ...
                char(obj.Path), ...
                assessmentBlock)

            continue;
        end

        p = ...
            double(obj.Port);

        if isempty(p) || ...
                ~isscalar(p) || ...
                ~isfinite(p)

            continue;
        end

        Port(end+1,1) = p; %#ok<AGROW>
        Symbol(end+1,1) = string(obj.Name); %#ok<AGROW>

    catch
    end
end

if isempty(Port)

    error( ...
        'No Assessment Input symbols with usable Port values: %s', ...
        assessmentBlock);
end

[Port, idx] = ...
    sort(Port);

Symbol = ...
    Symbol(idx);

if numel(unique(Port)) ~= numel(Port)

    error( ...
        'Duplicate Assessment Stateflow.Data.Port values were found.');
end

A = ...
    table( ...
        Port, ...
        Symbol, ...
        'VariableNames', { ...
            'AssessmentPort', ...
            'AssessmentSymbol'});

end


%% ============================================================
% Signal Editor active scenario element names
%% ============================================================

function [names, scenarioName, matPath] = ...
    collect_signal_editor_scenario_names( ...
        harnessName, ...
        topModel)

sigBlock = ...
    st_find_signal_editor_block( ...
        harnessName);

scenarioName = ...
    char( ...
        get_param( ...
            sigBlock, ...
            'ActiveScenario'));

if isempty(scenarioName)

    error( ...
        'Signal Editor ActiveScenario is empty: %s', ...
        sigBlock);
end

fileName = ...
    get_param( ...
        sigBlock, ...
        'Filename');

matPath = ...
    st_resolve_data_file( ...
        fileName, ...
        topModel);

if ~isfile(matPath)

    error( ...
        'Signal Editor data file not found: %s', ...
        matPath);
end

S = ...
    load( ...
        matPath, ...
        scenarioName);

if ~isfield(S, scenarioName)

    error( ...
        'Active scenario variable not found in MAT file: %s', ...
        scenarioName);
end

scenario = ...
    S.(scenarioName);

names = ...
    scenario_element_names( ...
        scenario);

end


function names = ...
    scenario_element_names( ...
        scenario)

names = ...
    strings(0,1);

% Primary path for Signal Editor data:
% Simulink.SimulationData.Dataset and compatible objects.
try

    rawNames = ...
        getElementNames( ...
            scenario);

    if ischar(rawNames)

        names = ...
            string({rawNames});

    else

        names = ...
            string(rawNames(:));
    end

    return;

catch
end

% Fallback: Dataset-style numElements/getElement access.
try

    n = ...
        scenario.numElements;

    temp = ...
        strings(n,1);

    for i = 1:n

        element = ...
            getElement( ...
                scenario, ...
                i);

        try

            temp(i) = ...
                string(element.Name);

        catch

            temp(i) = ...
                sprintf( ...
                    '<ScenarioElement%d>', ...
                    i);
        end
    end

    names = ...
        temp;

    return;

catch
end

error( ...
    ['Could not read Signal Editor scenario element names. ' ...
     'Scenario class: %s'], ...
    class(scenario));

end


function st_close_harness_quiet( ...
        ownerPath, ...
        harnessName)

try

    sltest.harness.close( ...
        ownerPath, ...
        harnessName);

catch
end

end
