function [ranking, excluded] = st_score_path_candidates( ...
        candidatePaths, ...
        excelRow, ...
        resolvedAnchors, ...
        modelName, ...
        anchorCount)
%ST_SCORE_PATH_CANDIDATES Rank ambiguous CUT paths with context awareness.
%
% The algorithm intentionally does NOT use Excel depth/indent information.
% Excel row order is used only as an ordering/context hint.
%
% Before recommendation scoring, a hard structural filter is applied:
%   If a later Excel CUT already has a confidently resolved path, the
%   current CUT candidate cannot be located under that later CUT path.
%
% Example:
%   Excel order: A, B, C, D, E
%   Resolved D : MODEL/A/C/D
%
%   Candidate B = MODEL/A/C/D/Internal/B
%   -> excluded before scoring because B is under later CUT D.
%
% After filtering, duplicated candidates are ranked using:
%   - a stable context root supported by several nearby resolved CUTs
%   - structural relation to individual resolved anchors
%   - Excel row proximity as a weak weighting factor
%
% Inputs
%   candidatePaths  : full Simulink paths for the current CUT name
%   excelRow        : physical Excel row of the current CUT
%   resolvedAnchors : table with ExcelRow, CUTName, CUTPath
%   modelName       : selected top model name
%   anchorCount     : number of nearby resolved anchors used for context
%
% Outputs
%   ranking  : remaining candidates sorted by recommendation score
%   excluded : candidates removed by the later-CUT hard filter

if nargin < 5 || isempty(anchorCount)
    anchorCount = 5;
end

candidatePaths = ...
    st_to_cellstr( ...
        candidatePaths);


%% ============================================================
% Hard filter using confidently resolved later CUTs
%% ============================================================

[keptPaths, excluded] = ...
    st_filter_later_cut_ancestors( ...
        candidatePaths, ...
        excelRow, ...
        resolvedAnchors, ...
        modelName);


%% ============================================================
% Empty result
%% ============================================================

if isempty(keptPaths)

    ranking = table( ...
        strings(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        zeros(0,1), ...
        strings(0,1), ...
        zeros(0,1), ...
        strings(0,1), ...
        nan(0,1), ...
        strings(0,1), ...
        'VariableNames', { ...
            'CandidatePath', ...
            'RelativePath', ...
            'Parent', ...
            'Grandparent', ...
            'Score', ...
            'ContextRoot', ...
            'ContextSupport', ...
            'BestAnchor', ...
            'BestAnchorRow', ...
            'BestRelation'});

    return;
end


%% ============================================================
% Select nearby anchors and derive stable context root
%% ============================================================

nearbyAnchors = ...
    st_select_nearby_anchors( ...
        resolvedAnchors, ...
        excelRow, ...
        anchorCount);

[contextRoot, contextSupport] = ...
    st_find_stable_context_root( ...
        nearbyAnchors, ...
        modelName);


%% ============================================================
% Score remaining candidates
%% ============================================================

n = numel(keptPaths);

CandidatePath = strings(n,1);
RelativePath = strings(n,1);
Parent = strings(n,1);
Grandparent = strings(n,1);
Score = zeros(n,1);
ContextRoot = strings(n,1);
ContextSupport = repmat(contextSupport, n, 1);
BestAnchor = strings(n,1);
BestAnchorRow = nan(n,1);
BestRelation = strings(n,1);

for i = 1:n

    candidate = ...
        keptPaths{i};

    CandidatePath(i) = ...
        string(candidate);

    RelativePath(i) = ...
        string( ...
            st_relative_model_path( ...
                candidate, ...
                modelName));

    [parentName, grandparentName] = ...
        st_parent_names( ...
            candidate);

    Parent(i) = ...
        string(parentName);

    Grandparent(i) = ...
        string(grandparentName);

    ContextRoot(i) = ...
        string( ...
            st_relative_model_path( ...
                contextRoot, ...
                modelName));


    %% --------------------------------------------------------
    % Stable context-root score
    %% --------------------------------------------------------

    contextScore = 0;

    if ~isempty(contextRoot)

        candidateParts = ...
            st_path_parts(candidate);

        contextParts = ...
            st_path_parts(contextRoot);

        commonDepth = ...
            st_common_prefix_depth( ...
                candidateParts, ...
                contextParts);

        if commonDepth == numel(contextParts)

            contextDepthBelowModel = ...
                max(numel(contextParts) - 1, 0);

            depthBelowContext = ...
                numel(candidateParts) - numel(contextParts);

            contextScore = ...
                45 + ...
                contextDepthBelowModel * 12 + ...
                contextSupport * 14;

            % A candidate can legitimately be several levels below the
            % context root, but excessive nesting gets a mild penalty so a
            % candidate that only follows one deep branch does not dominate.
            contextScore = ...
                contextScore - ...
                max(depthBelowContext - 3, 0) * 4;
        end
    end


    %% --------------------------------------------------------
    % Individual-anchor support score
    %% --------------------------------------------------------

    anchorScore = 0;

    if ~isempty(nearbyAnchors) && ...
            height(nearbyAnchors) > 0

        perAnchorScores = ...
            zeros(height(nearbyAnchors),1);

        relations = ...
            strings(height(nearbyAnchors),1);

        for a = 1:height(nearbyAnchors)

            anchorPath = ...
                char(nearbyAnchors.CUTPath(a));

            anchorRow = ...
                double(nearbyAnchors.ExcelRow(a));

            rowDelta = ...
                abs(excelRow - anchorRow);

            [structuralScore, relation] = ...
                st_path_relation_score( ...
                    candidate, ...
                    anchorPath);

            % Excel row distance is intentionally weak. It improves local
            % navigation without implying parent/child hierarchy.
            rowWeight = ...
                1 / (1 + 0.25 * max(rowDelta - 1, 0));

            perAnchorScores(a) = ...
                structuralScore * rowWeight;

            relations(a) = ...
                string(relation);
        end

        [sortedScores, order] = ...
            sort( ...
                perAnchorScores, ...
                'descend');

        keepCount = ...
            min( ...
                3, ...
                numel(sortedScores));

        if keepCount > 0

            weights = ...
                [1.00 0.45 0.20];

            anchorScore = ...
                sum( ...
                    sortedScores(1:keepCount).' .* ...
                    weights(1:keepCount));

            bestIndex = ...
                order(1);

            BestAnchor(i) = ...
                string( ...
                    st_relative_model_path( ...
                        char(nearbyAnchors.CUTPath(bestIndex)), ...
                        modelName));

            BestAnchorRow(i) = ...
                double(nearbyAnchors.ExcelRow(bestIndex));

            BestRelation(i) = ...
                relations(bestIndex);
        end
    end


    %% --------------------------------------------------------
    % Final score
    %% --------------------------------------------------------

    Score(i) = ...
        max( ...
            contextScore + anchorScore, ...
            0);
end


%% ============================================================
% Result / sort
%% ============================================================

ranking = table( ...
    CandidatePath, ...
    RelativePath, ...
    Parent, ...
    Grandparent, ...
    Score, ...
    ContextRoot, ...
    ContextSupport, ...
    BestAnchor, ...
    BestAnchorRow, ...
    BestRelation);

[~, order] = ...
    sortrows( ...
        [ranking.Score, -double((1:height(ranking)).')], ...
        [-1 -1]);

ranking = ...
    ranking(order,:);

end


%% ============================================================
% Hard filter
%% ============================================================

function [keptPaths, excluded] = ...
    st_filter_later_cut_ancestors( ...
        candidatePaths, ...
        excelRow, ...
        resolvedAnchors, ...
        modelName)

keptPaths = {};

CandidatePath = strings(0,1);
RelativePath = strings(0,1);
LaterCUT = strings(0,1);
LaterExcelRow = zeros(0,1);
LaterCUTPath = strings(0,1);
Reason = strings(0,1);

if isempty(resolvedAnchors) || ...
        height(resolvedAnchors) == 0

    keptPaths = ...
        candidatePaths;

    excluded = table( ...
        CandidatePath, ...
        RelativePath, ...
        LaterCUT, ...
        LaterExcelRow, ...
        LaterCUTPath, ...
        Reason);

    return;
end

laterMask = ...
    double(resolvedAnchors.ExcelRow) > excelRow;

laterAnchors = ...
    resolvedAnchors(laterMask,:);

for i = 1:numel(candidatePaths)

    candidate = ...
        candidatePaths{i};

    excludedBy = [];

    for a = 1:height(laterAnchors)

        laterPath = ...
            char(laterAnchors.CUTPath(a));

        if st_is_strict_descendant_path( ...
                candidate, ...
                laterPath)

            excludedBy = a;
            break;
        end
    end

    if isempty(excludedBy)

        keptPaths{end+1,1} = ...
            candidate; %#ok<AGROW>

    else

        CandidatePath(end+1,1) = ...
            string(candidate); %#ok<AGROW>

        RelativePath(end+1,1) = ...
            string( ...
                st_relative_model_path( ...
                    candidate, ...
                    modelName)); %#ok<AGROW>

        LaterCUT(end+1,1) = ...
            string(laterAnchors.CUTName(excludedBy)); %#ok<AGROW>

        LaterExcelRow(end+1,1) = ...
            double(laterAnchors.ExcelRow(excludedBy)); %#ok<AGROW>

        LaterCUTPath(end+1,1) = ...
            string( ...
                st_relative_model_path( ...
                    char(laterAnchors.CUTPath(excludedBy)), ...
                    modelName)); %#ok<AGROW>

        Reason(end+1,1) = ...
            'CURRENT_CUT_UNDER_LATER_RESOLVED_CUT'; %#ok<AGROW>
    end
end

excluded = table( ...
    CandidatePath, ...
    RelativePath, ...
    LaterCUT, ...
    LaterExcelRow, ...
    LaterCUTPath, ...
    Reason);

end


function tf = ...
    st_is_strict_descendant_path( ...
        childPath, ...
        parentPath)

child = ...
    st_normalize_simulink_path(childPath);

parent = ...
    st_normalize_simulink_path(parentPath);

if isempty(child) || ...
        isempty(parent) || ...
        strcmp(child, parent)

    tf = false;
    return;
end

prefix = ...
    [parent '/'];

tf = ...
    length(child) > length(prefix) && ...
    strncmp(child, prefix, length(prefix));

end


%% ============================================================
% Nearby anchors / stable context root
%% ============================================================

function anchors = ...
    st_select_nearby_anchors( ...
        resolvedAnchors, ...
        excelRow, ...
        anchorCount)

if isempty(resolvedAnchors) || ...
        height(resolvedAnchors) == 0

    anchors = ...
        resolvedAnchors;

    return;
end

rowDistance = ...
    abs( ...
        double(resolvedAnchors.ExcelRow) - ...
        double(excelRow));

[~, order] = ...
    sort( ...
        rowDistance, ...
        'ascend');

keepCount = ...
    min( ...
        max(round(anchorCount), 1), ...
        numel(order));

anchors = ...
    resolvedAnchors(order(1:keepCount),:);

end


function [contextRoot, supportCount] = ...
    st_find_stable_context_root( ...
        anchors, ...
        modelName)
% Find the deepest ancestor path supported by at least two nearby anchors.
% This avoids treating one recently selected deep branch as the whole
% navigation context.

contextRoot = '';
supportCount = 0;

if isempty(anchors) || ...
        height(anchors) < 2

    return;
end

allParts = ...
    cell(height(anchors),1);

for i = 1:height(anchors)

    allParts{i} = ...
        st_path_parts( ...
            char(anchors.CUTPath(i)));
end

candidateRoots = {};

for i = 1:numel(allParts)

    parts = ...
        allParts{i};

    % Ignore model-only root. Start from one level below the model.
    for depth = 2:max(numel(parts) - 1, 2)

        if depth > numel(parts)
            break;
        end

        root = ...
            strjoin( ...
                parts(1:depth), ...
                '/');

        candidateRoots{end+1,1} = ...
            root; %#ok<AGROW>
    end
end

if isempty(candidateRoots)
    return;
end

candidateRoots = ...
    unique( ...
        candidateRoots, ...
        'stable');

bestValue = -Inf;

for r = 1:numel(candidateRoots)

    root = ...
        candidateRoots{r};

    support = 0;

    for a = 1:height(anchors)

        anchorPath = ...
            char(anchors.CUTPath(a));

        if strcmp( ...
                st_normalize_simulink_path(anchorPath), ...
                st_normalize_simulink_path(root)) || ...
                st_is_strict_descendant_path( ...
                    anchorPath, ...
                    root)

            support = support + 1;
        end
    end

    if support < 2
        continue;
    end

    depthBelowModel = ...
        max(numel(st_path_parts(root)) - 1, 0);

    % Support is more important than depth. Depth breaks ties between roots
    % supported by the same number of nearby anchors.
    value = ...
        support * 100 + ...
        depthBelowModel * 10;

    if value > bestValue

        bestValue = value;
        contextRoot = root;
        supportCount = support;
    end
end

if isempty(contextRoot)

    modelOnly = ...
        char(modelName);

    common = ...
        allParts{1};

    for i = 2:numel(allParts)

        depth = ...
            st_common_prefix_depth( ...
                common, ...
                allParts{i});

        common = ...
            common(1:depth);

        if numel(common) <= 1
            break;
        end
    end

    if numel(common) > 1

        contextRoot = ...
            strjoin(common, '/');

        supportCount = ...
            height(anchors);

    else

        contextRoot = modelOnly;
        supportCount = 0;
    end
end

end


%% ============================================================
% Structural relation score
%% ============================================================

function [score, relation] = ...
    st_path_relation_score( ...
        candidatePath, ...
        anchorPath)

candidateParts = ...
    st_path_parts(candidatePath);

anchorParts = ...
    st_path_parts(anchorPath);

commonDepth = ...
    st_common_prefix_depth( ...
        candidateParts, ...
        anchorParts);

commonBelowModel = ...
    max(commonDepth - 1, 0);

treeDistance = ...
    (numel(candidateParts) - commonDepth) + ...
    (numel(anchorParts) - commonDepth);

candidateIsDescendant = ...
    numel(candidateParts) > numel(anchorParts) && ...
    commonDepth == numel(anchorParts);

candidateIsAncestor = ...
    numel(anchorParts) > numel(candidateParts) && ...
    commonDepth == numel(candidateParts);

sameParent = ...
    numel(candidateParts) >= 2 && ...
    numel(anchorParts) >= 2 && ...
    st_parts_equal( ...
        candidateParts(1:end-1), ...
        anchorParts(1:end-1));

sameGrandparent = false;

if numel(candidateParts) >= 3 && ...
        numel(anchorParts) >= 3

    sameGrandparent = ...
        st_parts_equal( ...
            candidateParts(1:end-2), ...
            anchorParts(1:end-2));
end

score = ...
    commonBelowModel * 10 - ...
    treeDistance * 2;

relation = ...
    'COMMON_ANCESTOR';

if candidateIsDescendant

    depthDifference = ...
        numel(candidateParts) - numel(anchorParts);

    score = ...
        score + ...
        80 + ...
        max(0, 18 - 4 * (depthDifference - 1));

    relation = ...
        'DESCENDANT_OF_ANCHOR';

elseif candidateIsAncestor

    depthDifference = ...
        numel(anchorParts) - numel(candidateParts);

    score = ...
        score + ...
        70 + ...
        max(0, 15 - 3 * (depthDifference - 1));

    relation = ...
        'ANCESTOR_OF_ANCHOR';

elseif sameParent

    score = ...
        score + 55;

    relation = ...
        'SAME_PARENT';

elseif sameGrandparent

    score = ...
        score + 30;

    relation = ...
        'SAME_GRANDPARENT';

elseif commonBelowModel == 0

    relation = ...
        'MODEL_ONLY';
end

score = ...
    max(score, 0);

end


%% ============================================================
% Path helpers
%% ============================================================

function out = ...
    st_normalize_simulink_path(value)

out = ...
    strrep( ...
        char(value), ...
        char(92), ...
        '/');

out = ...
    strtrim(out);

while ~isempty(out) && ...
        out(1) == '/'

    out(1) = [];
end

while ~isempty(out) && ...
        out(end) == '/'

    out(end) = [];
end

end


function parts = ...
    st_path_parts(pathValue)

pathValue = ...
    st_normalize_simulink_path(pathValue);

if isempty(pathValue)

    parts = {};

else

    parts = ...
        strsplit( ...
            pathValue, ...
            '/');
end

end


function depth = ...
    st_common_prefix_depth(a, b)

limit = ...
    min(numel(a), numel(b));

depth = 0;

for i = 1:limit

    if strcmp(a{i}, b{i})

        depth = depth + 1;

    else

        break;
    end
end

end


function tf = ...
    st_parts_equal(a, b)

if numel(a) ~= numel(b)

    tf = false;
    return;
end

tf = ...
    all(strcmp(a, b));

end


function [parentName, grandparentName] = ...
    st_parent_names(pathValue)

parts = ...
    st_path_parts(pathValue);

parentName = '';
grandparentName = '';

if numel(parts) >= 2

    parentName = ...
        parts{end-1};
end

if numel(parts) >= 3

    grandparentName = ...
        parts{end-2};
end

end


function relative = ...
    st_relative_model_path( ...
        pathValue, ...
        modelName)

pathValue = ...
    st_normalize_simulink_path(pathValue);

modelName = ...
    st_normalize_simulink_path(modelName);

if isempty(pathValue)

    relative = '';
    return;
end

if strcmp(pathValue, modelName)

    relative = modelName;
    return;
end

prefix = ...
    [modelName '/'];

if length(pathValue) >= length(prefix) && ...
        strncmp(pathValue, prefix, length(prefix))

    relative = ...
        pathValue(length(prefix)+1:end);

else

    relative = ...
        pathValue;
end

end


function c = ...
    st_to_cellstr(value)

if isempty(value)

    c = {};

elseif iscell(value)

    c = ...
        cellfun( ...
            @char, ...
            value(:), ...
            'UniformOutput', false);

elseif isstring(value)

    c = ...
        cellstr(value(:));

elseif ischar(value)

    c = {value};

else

    c = ...
        cellstr(string(value(:)));
end

end
