function R = st_validate_scenario_alignment()
%ST_VALIDATE_SCENARIO_ALIGNMENT
% Validate one-to-one SLDV scenario alignment before test execution.
%
% For FILE / GENERATE targets:
%
%   SLDV profile ScenarioNames
%       == Signal Editor scenarios
%       == Test Assessment scenarios
%       == Test Manager table iterations
%
% Scenario order is not used as the matching key here. Names and counts must
% match exactly as a set because later execution/update logic selects each
% iteration and Assessment scenario by UT_REQ_{CUTName}_{NNN}.
%
% OFF mode is intentionally skipped to preserve the legacy single-scenario
% workflow, including no-direct-Inport behavior.

cfg = st_require_runtime_target();
T = st_load_targets(cfg.OnlyEnabled);

n = height(T);

ExpectedScenarioCount = zeros(n,1);
SignalEditorScenarioCount = zeros(n,1);
AssessmentScenarioCount = zeros(n,1);
TestManagerIterationCount = zeros(n,1);
SignalEditorScenarioParameterCount = zeros(n,1);
TestSequenceScenarioParameterCount = zeros(n,1);

ExpectedScenarios = strings(n,1);
SignalEditorScenarios = strings(n,1);
AssessmentScenarios = strings(n,1);
TestManagerIterations = strings(n,1);

Status = strings(n,1);
Message = strings(n,1);
ElapsedSec = zeros(n,1);
Timestamp = strings(n,1);

if ~isfile(cfg.TestFile)
    error( ...
        'Test File을 찾을 수 없습니다: %s', ...
        cfg.TestFile);
end

tf = ...
    sltest.testmanager.TestFile( ...
        cfg.TestFile);

ts = ...
    getTestSuiteByName( ...
        tf, ...
        cfg.TestSuiteName);

if isempty(ts)
    error( ...
        'Test Suite를 찾을 수 없습니다: %s', ...
        cfg.TestSuiteName);
end

if numel(ts) ~= 1
    error( ...
        '동일한 이름의 Test Suite가 여러 개 있습니다: %s', ...
        cfg.TestSuiteName);
end

fprintf('\n');
fprintf('============================================\n');
fprintf('Validate Scenario Alignment\n');
fprintf('============================================\n');

totalTimer = tic;

st_log(cfg, 'INFO', ...
    'Scenario alignment validation start | count=%d', ...
    n);

for i = 1:n

    timerValue = tic;

    ownerPath = ...
        st_normalize_cut_path( ...
            T.CUTPath(i), ...
            cfg.TopModel);

    harnessName = ...
        char(T.HarnessName(i));

    testCaseName = ...
        char(T.TestCaseName(i));

    profile = ...
        st_get_sldv_profile( ...
            T(i,:), ...
            cfg);

    expected = ...
        normalize_cellstr( ...
            profile.ScenarioNames);

    ExpectedScenarioCount(i) = ...
        numel(expected);

    ExpectedScenarios(i) = ...
        string(strjoin(expected, ', '));

    st_log(cfg, 'DEBUG', ...
        ['[ScenarioAlign %d/%d] start | CUT=%s | Harness=%s | ' ...
         'TestCase=%s | Mode=%s | Expected=[%s]'], ...
        i, n, ownerPath, harnessName, testCaseName, ...
        profile.Mode, strjoin(expected, ', '));

    try

        if strcmp(profile.Mode, 'OFF')

            Status(i) = 'SKIP';
            Message(i) = 'OFF mode uses the legacy scenario workflow';

            fprintf( ...
                '[%d/%d] SKIP %s | Mode=OFF\n', ...
                i, n, char(T.CUTName(i)));

            continue;
        end

        if isempty(expected)

            error( ...
                'SLDV profile has no ScenarioNames.');
        end

        assert_unique_names( ...
            expected, ...
            'Expected SLDV scenarios');


        %% ====================================================
        % Signal Editor
        %% ====================================================

        st_force_model_stopped( ...
            cfg.TopModel);

        st_log(cfg, 'DEBUG', ...
            '[ScenarioAlign %d/%d] harness.load start', ...
            i, n);

        sltest.harness.load( ...
            ownerPath, ...
            harnessName);

        st_log(cfg, 'DEBUG', ...
            '[ScenarioAlign %d/%d] harness.load done', ...
            i, n);

        sigBlock = ...
            st_find_signal_editor_block( ...
                harnessName);

        signalEditorNames = ...
            st_normalize_options( ...
                get_param( ...
                    sigBlock, ...
                    'options@ActiveScenario'));

        signalEditorNames = ...
            normalize_cellstr( ...
                signalEditorNames);

        SignalEditorScenarioCount(i) = ...
            numel(signalEditorNames);

        SignalEditorScenarios(i) = ...
            string(strjoin(signalEditorNames, ', '));

        st_log(cfg, 'DEBUG', ...
            '[ScenarioAlign %d/%d] SignalEditor count=%d | names=[%s]', ...
            i, n, numel(signalEditorNames), ...
            strjoin(signalEditorNames, ', '));

        assert_same_scenario_set( ...
            expected, ...
            signalEditorNames, ...
            'Signal Editor');


        %% ====================================================
        % Test Assessment
        %% ====================================================

        assess = ...
            st_find_assessment_block( ...
                harnessName);

        if ~sltest.testsequence.isUsingScenarios(assess)

            error( ...
                'Test Assessment is not using scenarios: %s', ...
                assess);
        end

        assessmentNames = ...
            normalize_cellstr( ...
                sltest.testsequence.getAllScenarios( ...
                    assess));

        AssessmentScenarioCount(i) = ...
            numel(assessmentNames);

        AssessmentScenarios(i) = ...
            string(strjoin(assessmentNames, ', '));

        st_log(cfg, 'DEBUG', ...
            '[ScenarioAlign %d/%d] Assessment count=%d | names=[%s]', ...
            i, n, numel(assessmentNames), ...
            strjoin(assessmentNames, ', '));

        assert_same_scenario_set( ...
            expected, ...
            assessmentNames, ...
            'Test Assessment');


        %% ====================================================
        % Test Manager
        %% ====================================================

        tc = ...
            getTestCaseByName( ...
                ts, ...
                testCaseName);

        if isempty(tc)

            error( ...
                'Test Case를 찾을 수 없습니다: %s', ...
                testCaseName);
        end

        if numel(tc) ~= 1

            error( ...
                '동일한 TestCaseName이 여러 개 있습니다: %s', ...
                testCaseName);
        end

        iterations = ...
            getIterations( ...
                tc);

        iterationNames = ...
            cell(numel(iterations),1);

        for k = 1:numel(iterations)

            iterationNames{k} = ...
                char(iterations(k).Name);
        end

        TestManagerIterationCount(i) = ...
            numel(iterationNames);

        TestManagerIterations(i) = ...
            string(strjoin(iterationNames, ', '));

        st_log(cfg, 'DEBUG', ...
            '[ScenarioAlign %d/%d] TestManager iterations=%d | names=[%s]', ...
            i, n, numel(iterationNames), ...
            strjoin(iterationNames, ', '));

        assert_same_scenario_set( ...
            expected, ...
            iterationNames, ...
            'Test Manager iterations');

        [SignalEditorScenarioParameterCount(i), ...
         TestSequenceScenarioParameterCount(i)] = ...
            assert_iteration_scenario_parameters( ...
                iterations, ...
                expected);


        %% ====================================================
        % Result
        %% ====================================================

        st_close_harness_quiet( ...
            ownerPath, ...
            harnessName);

        Status(i) = 'OK';

        Message(i) = ...
            sprintf( ...
                ['expected=%d, signalEditor=%d, assessment=%d, ' ...
                 'iterations=%d'], ...
                numel(expected), ...
                numel(signalEditorNames), ...
                numel(assessmentNames), ...
                numel(iterationNames));

        fprintf( ...
            ['[%d/%d] OK   %s | expected=%d | ' ...
             'SignalEditor=%d | Assessment=%d | Iterations=%d\n'], ...
            i, n, char(T.CUTName(i)), ...
            numel(expected), ...
            numel(signalEditorNames), ...
            numel(assessmentNames), ...
            numel(iterationNames));

    catch ME

        st_close_harness_quiet( ...
            ownerPath, ...
            harnessName);

        Status(i) = 'FAIL';
        Message(i) = string(ME.message);

        st_log(cfg, 'ERROR', ...
            '[ScenarioAlign %d/%d] %s', ...
            i, n, ME.message);

        fprintf( ...
            '[%d/%d] FAIL %s | %s\n', ...
            i, n, char(T.CUTName(i)), ME.message);
    end

    ElapsedSec(i) = ...
        toc(timerValue);

    Timestamp(i) = ...
        string( ...
            datetime( ...
                'now', ...
                'Format', ...
                'yyyy-MM-dd HH:mm:ss'));

    st_log(cfg, 'DEBUG', ...
        ['[ScenarioAlign %d/%d] finished | status=%s | ' ...
         'elapsed=%.3f sec | total=%.3f sec'], ...
        i, n, char(Status(i)), ...
        ElapsedSec(i), toc(totalTimer));
end

R = table( ...
    T.No, ...
    T.CUTName, ...
    T.HarnessName, ...
    T.TestCaseName, ...
    T.SldvMode, ...
    ExpectedScenarioCount, ...
    SignalEditorScenarioCount, ...
    AssessmentScenarioCount, ...
    TestManagerIterationCount, ...
    SignalEditorScenarioParameterCount, ...
    TestSequenceScenarioParameterCount, ...
    ExpectedScenarios, ...
    SignalEditorScenarios, ...
    AssessmentScenarios, ...
    TestManagerIterations, ...
    Status, ...
    Message, ...
    ElapsedSec, ...
    Timestamp, ...
    'VariableNames', { ...
        'No', ...
        'CUTName', ...
        'HarnessName', ...
        'TestCaseName', ...
        'SldvMode', ...
        'ExpectedScenarioCount', ...
        'SignalEditorScenarioCount', ...
        'AssessmentScenarioCount', ...
        'TestManagerIterationCount', ...
        'SignalEditorScenarioParameterCount', ...
        'TestSequenceScenarioParameterCount', ...
        'ExpectedScenarios', ...
        'SignalEditorScenarios', ...
        'AssessmentScenarios', ...
        'TestManagerIterations', ...
        'Status', ...
        'Message', ...
        'ElapsedSec', ...
        'Timestamp'});

st_write_result( ...
    'ScenarioAlignmentResult', ...
    R);

fprintf('\n');
fprintf('============================================\n');
fprintf('Scenario Alignment Result\n');
fprintf('============================================\n');
fprintf('OK   : %d\n', sum(strcmp(Status, 'OK')));
fprintf('SKIP : %d\n', sum(strcmp(Status, 'SKIP')));
fprintf('FAIL : %d\n', sum(strcmp(Status, 'FAIL')));
fprintf('Total: %d\n', n);
fprintf('============================================\n');

st_log(cfg, 'INFO', ...
    'Scenario alignment validation complete | elapsed=%.3f sec', ...
    toc(totalTimer));

end


function [signalEditorCount, testSequenceCount] = ...
        assert_iteration_scenario_parameters(iterations, expected)
%ASSERT_ITERATION_SCENARIO_PARAMETERS
% Every SLDV iteration must bind both scenario consumers to its own name.

signalEditorCount = 0;
testSequenceCount = 0;
expected = normalize_cellstr(expected);

for i = 1:numel(iterations)
    scenarioName = char(iterations(i).Name);

    if ~ismember(scenarioName, expected)
        error( ...
            'Iteration has an unexpected name: %s', ...
            scenarioName);
    end

    testParams = iterations(i).TestParams;

    % R2025b exposes the Signal Editor scenario iteration parameter as
    % SignalBuilderGroup in TestParams.  Earlier releases and the creation
    % API use SignalEditorScenario. Both names represent the same binding.
    if ~test_param_matches_any_scenario( ...
            testParams, ...
            {'SignalEditorScenario', 'SignalBuilderGroup'}, ...
            scenarioName)
        error( ...
            ['Test Manager Iteration %s does not bind ' ...
             'the Signal Editor scenario to the same scenario. TestParams=%s'], ...
            scenarioName, ...
            test_params_to_text(testParams));
    end

    if ~test_param_matches_scenario( ...
            testParams, ...
            'TestSequenceScenario', ...
            scenarioName)
        error( ...
            ['Test Manager Iteration %s does not bind ' ...
             'TestSequenceScenario to the same scenario. TestParams=%s'], ...
            scenarioName, ...
            test_params_to_text(testParams));
    end

    signalEditorCount = signalEditorCount + 1;
    testSequenceCount = testSequenceCount + 1;
end

end


function tf = test_param_matches_any_scenario( ...
        testParams, parameterNames, scenarioName)

tf = false;
for i = 1:numel(parameterNames)
    if test_param_matches_scenario( ...
            testParams, parameterNames{i}, scenarioName)
        tf = true;
        return;
    end
end
end


function tf = test_param_matches_scenario(testParams, parameterName, scenarioName)

entries = test_params_to_entries(testParams);
tf = false;

for i = 1:numel(entries)
    if ~contains(entries{i}, parameterName)
        continue;
    end

    if contains(entries{i}, scenarioName)
        tf = true;
        return;
    end

    % Some releases expose TestParams as adjacent name/value cell entries.
    if i < numel(entries) && contains(entries{i + 1}, scenarioName)
        tf = true;
        return;
    end
end

end


function entries = test_params_to_entries(value)

if isempty(value)
    entries = {};
elseif iscell(value)
    entries = cell(numel(value), 1);
    for i = 1:numel(value)
        entries{i} = test_params_to_text(value{i});
    end
else
    entries = {test_params_to_text(value)};
end

end


function text = test_params_to_text(value)

if isempty(value)
    text = '';
elseif iscell(value)
    parts = cellfun(@test_params_to_text, value(:), ...
        'UniformOutput', false);
    text = strjoin(parts, ' | ');
elseif isstruct(value)
    fields = fieldnames(value);
    parts = cell(1, numel(fields));
    for i = 1:numel(fields)
        parts{i} = [fields{i} '=' test_params_to_text(value.(fields{i}))];
    end
    text = strjoin(parts, ', ');
else
    try
        text = char(string(value));
    catch
        text = class(value);
    end
end

end


function assert_same_scenario_set( ...
        expected, ...
        actual, ...
        label)

expected = ...
    normalize_cellstr(expected);

actual = ...
    normalize_cellstr(actual);

assert_unique_names( ...
    actual, ...
    label);

if numel(expected) ~= numel(actual)

    error( ...
        ['%s scenario count mismatch. ' ...
         'Expected=%d [%s], Actual=%d [%s]'], ...
        label, ...
        numel(expected), ...
        strjoin(expected, ', '), ...
        numel(actual), ...
        strjoin(actual, ', '));
end

expectedSorted = ...
    sort(string(expected(:)));

actualSorted = ...
    sort(string(actual(:)));

if ~isequal( ...
        expectedSorted, ...
        actualSorted)

    error( ...
        ['%s scenario names mismatch. ' ...
         'Expected=[%s], Actual=[%s]'], ...
        label, ...
        strjoin(expected, ', '), ...
        strjoin(actual, ', '));
end

end


function assert_unique_names(names, label)

names = ...
    normalize_cellstr(names);

if numel(unique(string(names))) ~= numel(names)

    error( ...
        '%s contains duplicate scenario names: [%s]', ...
        label, ...
        strjoin(names, ', '));
end

end


function c = normalize_cellstr(v)

if isempty(v)

    c = {};

elseif iscell(v)

    c = ...
        cellfun( ...
            @(x) char(string(x)), ...
            v(:), ...
            'UniformOutput', ...
            false);

elseif isstring(v)

    c = ...
        cellstr(v(:));

elseif ischar(v)

    c = ...
        {v};

else

    c = ...
        cellstr(string(v(:)));
end

end


function st_close_harness_quiet( ...
        ownerPath, ...
        harnessName)

try

    sltest.harness.close( ...
        ownerPath, ...
        harnessName);

catch
end

end
